# Generated by Django 4.2.1 on 2024-08-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_alter_pipeline_last_run_status"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                db_comment="Foreign key reference to the Pipeline model.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pipeline.pipeline",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="api",
            field=models.ForeignKey(
                blank=True,
                db_comment="Foreign key reference to the APIDeployment model.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.apideployment",
            ),
        ),
    ]
