# Generated by Django 4.2.1 on 2024-01-23 11:18

import uuid

import connector.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflow", "0001_initial"),
        ("connector_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectorInstance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("connector_name", models.TextField(max_length=128)),
                ("connector_id", models.CharField(default="", max_length=128)),
                (
                    "connector_metadata",
                    connector.fields.ConnectorAuthJSONField(
                        db_column="connector_metadata", default=dict
                    ),
                ),
                (
                    "connector_version",
                    models.CharField(default="", max_length=64),
                ),
                (
                    "connector_type",
                    models.CharField(
                        choices=[("INPUT", "Input"), ("OUTPUT", "Output")]
                    ),
                ),
                (
                    "connector_mode",
                    models.CharField(
                        choices=[
                            (0, "UNKNOWN"),
                            (1, "FILE_SYSTEM"),
                            (2, "DATABASE"),
                        ],
                        db_comment="0: UNKNOWN, 1: FILE_SYSTEM, 2: DATABASE",
                        default=0,
                    ),
                ),
                (
                    "connector_auth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="connector_auth.connectorauth",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_connectors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_connectors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_connectors",
                        to="project.project",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_connectors",
                        to="workflow.workflow",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="connectorinstance",
            constraint=models.UniqueConstraint(
                fields=("connector_name", "workflow", "connector_type"),
                name="unique_connector",
            ),
        ),
    ]
