# Generated by Django 4.2.1 on 2024-02-28 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector", "0002_connectorinstance_connector_metadata_b"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectorinstance",
            name="connector_metadata",
        ),
        migrations.RemoveField(
            model_name="connectorinstance",
            name="connector_metadata_b",
        ),
    ]
