# Generated by Django 4.2.1 on 2024-02-28 05:13

import connector.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connector", "0002_connectorinstance_connector_metadata_b"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectorinstance",
            name="connector_metadata",
            field=connector.models.EncryptedField(null=True),
        ),
    ]
