# Generated by Django 4.2.1 on 2024-02-28 12:37

import connector.fields
import django_cryptography.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "connector",
            "0003_remove_connectorinstance_connector_metadata_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="connectorinstance",
            name="connector_metadata",
            field=django_cryptography.fields.encrypt(
                connector.fields.ConnectorAuthJSONField(
                    db_column="connector_metadata", default=dict
                )
            ),
        ),
    ]
