# Generated by Django migration for centralized connectors (simplified)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('connector_v2', '0001_initial'),
    ]

    operations = [
        # Add is_shared field
        migrations.AddField(
            model_name='connectorinstance',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='True for centralized connectors, False for workflow-specific connectors'),
        ),
        
        # Make workflow field nullable to support shared connectors
        migrations.AlterField(
            model_name='connectorinstance',
            name='workflow',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='connector_workflow',
                to='workflow_v2.workflow'
            ),
        ),
        
        # Remove old unique constraint
        migrations.RemoveConstraint(
            model_name='connectorinstance',
            name='unique_workflow_connector',
        ),
    ]