# Generated by Django 4.2.1 on 2025-07-22 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connector_v2", "0003_migrate_to_centralized_connectors"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="connectorinstance",
            name="unique_workflow_connector",
        ),
        migrations.RemoveField(
            model_name="connectorinstance",
            name="connector_type",
        ),
        migrations.RemoveField(
            model_name="connectorinstance",
            name="workflow",
        ),
        migrations.AddConstraint(
            model_name="connectorinstance",
            constraint=models.UniqueConstraint(
                fields=("connector_name", "organization"),
                name="unique_organization_connector",
            ),
        ),
        migrations.AddField(
            model_name="connectorinstance",
            name="shared_to_org",
            field=models.BooleanField(
                db_comment="Is the connector shared to entire org", default=False
            ),
        ),
        migrations.AddField(
            model_name="connectorinstance",
            name="shared_users",
            field=models.ManyToManyField(
                related_name="shared_connectors",
                to=settings.AUTH_USER_MODEL,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="connectorinstance",
            name="connector_mode",
            field=models.CharField(
                blank=True,
                choices=[(0, "UNKNOWN"), (1, "FILE_SYSTEM"), (2, "DATABASE")],
                db_comment="0: UNKNOWN, 1: FILE_SYSTEM, 2: DATABASE",
                default=0,
                null=True,
            ),
        ),
    ]
