# Generated by Django 4.2.1 on 2025-07-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connector_v2", "0003_migrate_to_centralized_connectors"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="connectorinstance",
            name="unique_workflow_connector",
        ),
        migrations.RemoveField(
            model_name="connectorinstance",
            name="connector_type",
        ),
        migrations.RemoveField(
            model_name="connectorinstance",
            name="workflow",
        ),
        migrations.AddConstraint(
            model_name="connectorinstance",
            constraint=models.UniqueConstraint(
                fields=("connector_name", "organization"),
                name="unique_organization_connector",
            ),
        ),
    ]
