# Generated by Django 4.2.1 on 2026-02-23 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connector_v2", "0005_fix_unintended_connector_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectorinstance",
            name="co_owners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users with full ownership privileges",
                related_name="co_owned_connectors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
