# Generated by Django 4.2.1 on 2026-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_account_v2", "0002_organization_group_group_membership"),
        ("connector_v2", "0005_fix_unintended_connector_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectorinstance",
            name="shared_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_connector_instances",
                to="tenant_account_v2.organizationgroup",
            ),
        ),
    ]
