# Generated by Django 4.2.1 on 2025-08-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_profile_manager_v2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemanager",
            name="is_summarize_llm",
            field=models.BooleanField(
                db_comment="DEPRECATED: Default LLM Profile used for summarizing. Use CustomTool.summarize_llm_adapter instead.",
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="profilemanager",
            name="retrieval_strategy",
            field=models.TextField(
                blank=True,
                default="simple",
                choices=[
                    ("simple", "Simple retrieval"),
                    ("subquestion", "Subquestion retrieval"),
                    ("fusion", "Fusion retrieval"),
                    ("recursive", "Recursive retrieval"),
                    ("router", "Router retrieval"),
                    ("keyword_table", "Keyword table retrieval"),
                    ("automerging", "Auto-merging retrieval"),
                ],
                db_comment="Field to store the retrieval strategy for prompts",
            ),
        ),
    ]
