# Generated by Django 4.2.1 on 2025-07-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_profile_manager_v2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemanager",
            name="is_summarize_llm",
            field=models.BooleanField(
                db_comment="DEPRECATED: Default LLM Profile used for summarizing. Use CustomTool.summarize_llm_adapter instead.",
                default=False,
            ),
        ),
    ]
