# Generated by Django 4.2.1 on 2025-08-05 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_profile_manager_v2", "0002_merged_retrieval_and_summarize"),
    ]

    operations = []
