# Generated by Django 4.2.1 on 2026-05-24 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prompt_profile_manager_v2", "0004_merge_20250805_1025"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemanager",
            name="shared_to_org",
            field=models.BooleanField(
                db_comment="Whether this profile is shared with the entire organization",
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="profilemanager",
            name="shared_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_profile_managers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
