# Generated by Django 4.2.1 on 2025-03-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_studio_index_manager_v2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexmanager",
            name="extraction_status",
            field=models.JSONField(
                db_comment="Extraction status for documents", default=dict
            ),
        ),
    ]
