# Generated by Django 4.2.1 on 2024-03-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio", "0005_alter_toolstudioprompt_enforce_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolstudioprompt",
            name="prompt_key",
            field=models.TextField(db_comment="Field to store the prompt key"),
        ),
        migrations.AddConstraint(
            model_name="toolstudioprompt",
            constraint=models.UniqueConstraint(
                fields=("prompt_key", "tool_id"),
                name="unique_prompt_key_tool_id",
            ),
        ),
    ]
