# Generated by Django 4.2.1 on 2024-07-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_studio", "0006_alter_toolstudioprompt_prompt_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toolstudioprompt",
            name="assert_prompt",
        ),
        migrations.RemoveField(
            model_name="toolstudioprompt",
            name="assertion_failure_prompt",
        ),
        migrations.RemoveField(
            model_name="toolstudioprompt",
            name="is_assert",
        ),
        migrations.AddField(
            model_name="toolstudioprompt",
            name="checked_in",
            field=models.BooleanField(
                db_comment="Currently checked-in prompt", default=True
            ),
        ),
        migrations.AddField(
            model_name="toolstudioprompt",
            name="loaded_version",
            field=models.CharField(
                db_comment="Current loaded version of prompt",
                default="v1",
                max_length=10,
            ),
        ),
    ]
