# Generated by Django 4.2.1 on 2024-04-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_studio", "0006_alter_toolstudioprompt_prompt_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolstudioprompt",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
