# Generated by Django 4.2.1 on 2024-07-08 05:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prompt_profile_manager", "0011_alter_profilemanager_retrieval_strategy"),
        ("prompt_studio", "0007_remove_toolstudioprompt_assert_prompt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptVersionManager",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_version_manager_id",
                    models.UUIDField(
                        db_comment="Field to store the UUID for the tag manager helper",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt_key",
                    models.TextField(db_comment="Field to store the prompt key"),
                ),
                (
                    "enforce_type",
                    models.TextField(
                        choices=[
                            ("Text", "Response sent as Text"),
                            ("number", "Response sent as number"),
                            ("email", "Response sent as email"),
                            ("date", "Response sent as date"),
                            ("boolean", "Response sent as boolean"),
                            ("json", "Response sent as json"),
                        ],
                        db_comment="Field to store the type in which the response to be returned.",
                        default="Text",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True, db_comment="Field to store the prompt"
                    ),
                ),
                ("version", models.CharField(max_length=10)),
                (
                    "profile_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_version_profile_manager",
                        to="prompt_profile_manager.profilemanager",
                    ),
                ),
                (
                    "prompt_id",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompt_studio.toolstudioprompt",
                    ),
                ),
            ],
            options={
                "db_table": "prompt_version_manager",
            },
        ),
        migrations.AddConstraint(
            model_name="promptversionmanager",
            constraint=models.UniqueConstraint(
                fields=("prompt_id", "version"), name="unique_prompt_id_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="promptversionmanager",
            constraint=models.UniqueConstraint(
                fields=(
                    "prompt_id",
                    "prompt_key",
                    "enforce_type",
                    "prompt",
                    "profile_manager",
                ),
                name="unique_prompt_fields",
            ),
        ),
    ]
