# Generated by Django 4.2.1 on 2024-06-18 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prompt_profile_manager", "0011_alter_profilemanager_retrieval_strategy"),
        ("prompt_studio", "0006_alter_toolstudioprompt_prompt_key_and_more"),
        ("prompt_studio_core", "0012_customtool_shared_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptVersionManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_key",
                    models.TextField(db_comment="Field to store the prompt key"),
                ),
                (
                    "enforce_type",
                    models.TextField(
                        choices=[
                            ("Text", "Response sent as Text"),
                            ("number", "Response sent as number"),
                            ("email", "Response sent as email"),
                            ("date", "Response sent as date"),
                            ("boolean", "Response sent as boolean"),
                            ("json", "Response sent as json"),
                        ],
                        db_comment="Field to store the type in which the response to be returned.",
                        default="Text",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True, db_comment="Field to store the prompt"
                    ),
                ),
                ("version", models.CharField(max_length=10)),
                (
                    "profile_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_version_profile_manager",
                        to="prompt_profile_manager.profilemanager",
                    ),
                ),
                (
                    "prompt_id",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompt_studio.toolstudioprompt",
                    ),
                ),
                (
                    "tool_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_version_tool_id",
                        to="prompt_studio_core.customtool",
                    ),
                ),
            ],
            options={
                "db_table": "prompt_version_manager",
            },
        ),
        migrations.AddConstraint(
            model_name="promptversionmanager",
            constraint=models.UniqueConstraint(
                fields=("tool_id", "prompt_id", "version"),
                name="unique_prompt_id_version",
            ),
        ),
    ]
