class CollectionKey:
    EXECUTE_API_KEY = "Process document"
    STATUS_API_KEY = "Execution status"
    STATUS_EXEC_ID_DEFAULT = "REPLACE_WITH_EXECUTION_ID"
    AUTH_QUERY_PARAM_DEFAULT = "REPLACE_WITH_API_KEY"
