version: '3.7'

services:
  mariadb:
    image: 'mariadb:11.2.4'
    container_name: unstract-mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env

  mysql:
    image: 'mysql:9.0.1'
    container_name: unstract-mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: unstract-mssql
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  sftp:
    image: atmoz/sftp:debian
    read_only: true
    ports:
    read_only: true
      - "22:22"
    read_only: true
    volumes:
    read_only: true
      - sftp_data:/home/foo
    read_only: true
    command: "${SFTP_USER}:${SFTP_PASS}:${SFTP_USER_ID}::${SFTP_DIR}"
    read_only: true

volumes:
  mariadb_data:
  mysql_data:
  mssql_data:
  sftp_data:
