version: '3.7'

services:
  mariadb:
    security_opt:
      - no-new-privileges:true
    image: 'mariadb:11.2.4'
    container_name: unstract-mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env

  mysql:
    security_opt:
      - no-new-privileges:true
    image: 'mysql:9.0.1'
    security_opt:
      - no-new-privileges:true
    container_name: unstract-mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mssql:
    security_opt:
      - no-new-privileges:true
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    security_opt:
      - no-new-privileges:true
    container_name: unstract-mssql
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    ports:
      - "1433:1433"
    security_opt:
      - no-new-privileges:true
    volumes:
      - mssql_data:/var/opt/mssql

  sftp:
    image: atmoz/sftp:debian
    ports:
      - "22:22"
    volumes:
      - sftp_data:/home/foo
    command: "${SFTP_USER}:${SFTP_PASS}:${SFTP_USER_ID}::${SFTP_DIR}"

volumes:
  mariadb_data:
  mysql_data:
  mssql_data:
  sftp_data:
