# Generated by Django 4.2.1 on 2023-08-21 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_auto_20230718_1040"),
        ("tenant_account", "0001_initial"),
    ]

    operations = [
        # # Commenting out here as this is taken care in 0001
        # migrations.CreateModel(
        #     name="OrganizationMember",
        #     fields=[
        #         (
        #             "user_ptr",
        #             models.OneToOneField(
        #                 auto_created=True,
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 parent_link=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 to=settings.AUTH_USER_MODEL,
        #             ),
        #         ),
        #         ("role", models.CharField(default="admin")),
        #     ],
        #     options={
        #         "verbose_name": "user",
        #         "verbose_name_plural": "users",
        #         "abstract": False,
        #     },
        #     bases=("account.user",),
        #     managers=[
        #         ("objects", django.contrib.auth.models.UserManager()),
        #     ],
        # ),
        # # https://www.geeksforgeeks.org/what-is-access-exclusive-lock-mode-in-postgreysql/
        # # commenting drop table to ignore AccesExclusive Lock
        # migrations.DeleteModel(
        #     name="User",
        # ),
    ]
