# Generated by Django 4.2.1 on 2024-05-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_account", "0005_organizationmember_is_onboarding_msg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmember",
            name="is_login_onboarding_msg",
            field=models.BooleanField(
                db_comment="Flag to indicate whether the onboarding messages are shown",
                default=True,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="is_prompt_studio_onboarding_msg",
            field=models.BooleanField(
                db_comment="Flag to indicate whether the prompt studio messages are shown",
                default=True,
            ),
        ),
    ]
