# Generated by Django 4.2.1 on 2024-01-20 08:04

import uuid

import django.db.models.deletion
import prompt_studio.prompt_studio_registry.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptStudioRegistry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_registry_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tool_property",
                    prompt_studio.prompt_studio_registry.fields.ToolPropertyJSONField(
                        db_column="tool_property", default=dict
                    ),
                ),
                (
                    "tool_spec",
                    prompt_studio.prompt_studio_registry.fields.ToolSpecJSONField(
                        db_column="tool_spec", default=dict
                    ),
                ),
                (
                    "tool_metadata",
                    prompt_studio.prompt_studio_registry.fields.ToolMetadataJSONField(
                        db_column="tool_metadata", default=dict
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        db_comment="Tool icon in svg format", editable=False
                    ),
                ),
                ("url", models.CharField(editable=False)),
                ("name", models.CharField(default="", editable=False)),
                ("description", models.CharField(default="", editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_registry_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_registry_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
