# Generated by Django 4.2.1 on 2024-02-06 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_core", "0003_merge_20240125_1501"),
        (
            "prompt_studio_registry",
            "0003_alter_promptstudioregistry_tool_metadata_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="promptstudioregistry",
            name="custom_tool",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_studio_registry",
                to="prompt_studio_core.customtool",
            ),
        )
    ]
