# Generated by Django 4.2.1 on 2024-02-06 19:36
from django.db import migrations, transaction
from tool_instance.exceptions import ToolDoesNotExist
from tool_instance.models import ToolInstance
from tool_instance.tool_processor import ToolProcessor


def populate_tool_instances(apps, schema_editor):
    ToolInstance = apps.get_model("tool_instance", "ToolInstance")

    # Get all tool instances
    tool_instances = ToolInstance.objects.all()
    with transaction.atomic():
        # Loop through each tool instance and call the function
        for tool_instance in tool_instances:
            try:
                # Call the function to lookup the tool by tool_id
                tool = ToolProcessor.get_tool_by_uid(tool_instance.tool_id)
            except ToolDoesNotExist as e:
                # Delete the tool_instance since its a stray exported tool
                tool_instance.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_registry", "0004_promptstudioregistry_custom_tool"),
        ("tool_instance", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_tool_instances)]
