# Generated by Django 4.2.1 on 2024-03-21 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prompt_studio_registry", "0005_delete_corrupt_tool_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptstudioregistry",
            name="shared_to_org",
            field=models.BooleanField(
                db_comment="Is the exported tool shared with entire org",
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="promptstudioregistry",
            name="shared_users",
            field=models.ManyToManyField(
                related_name="shared_exported_tools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
