# Generated by Django 4.2.1 on 2024-01-23 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_profile_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilemanager",
            old_name="updated_at",
            new_name="modified_at",
        ),
    ]
