# Generated by Django 4.2.1 on 2024-01-24 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adapter_processor", "0002_adapterinstance_unique_adapter"),
        ("prompt_profile_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilemanager",
            name="vector_size",
        ),
        migrations.AlterField(
            model_name="profilemanager",
            name="embedding_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile_manager_embedding",
                to="adapter_processor.adapterinstance",
            ),
        ),
        migrations.AlterField(
            model_name="profilemanager",
            name="llm",
            field=models.ForeignKey(
                db_comment="Field to store the LLM chosen by the user",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile_manager_llm",
                to="adapter_processor.adapterinstance",
            ),
        ),
        migrations.AlterField(
            model_name="profilemanager",
            name="vector_store",
            field=models.ForeignKey(
                db_comment="Field to store the chosen vector store.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile_manager_vector",
                to="adapter_processor.adapterinstance",
            ),
        ),
    ]
