# Generated by Django 4.2.1 on 2024-01-25 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "prompt_profile_manager",
            "0002_remove_profilemanager_vector_size_and_more",
        ),
        (
            "prompt_profile_manager",
            "0002_rename_updated_at_profilemanager_modified_at",
        ),
    ]

    operations = []
