# Generated by Django 4.2.1 on 2024-02-23 17:02

import django.db.models.deletion
from django.db import connection, migrations, models


def enable_triggers(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE adapter_adapterinstance ENABLE TRIGGER ALL;"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("adapter_processor", "0004_alter_adapterinstance_adapter_type"),
        (
            "prompt_profile_manager",
            "0005_removed_converter_and_added_x2text_foreign_key",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemanager",
            name="x2text",
            field=models.ForeignKey(
                db_comment="Field to store the X2Text Adapter chosen by the user",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile_manager_x2text",
                to="adapter_processor.adapterinstance",
            ),
        ),
        migrations.RunPython(
            enable_triggers,
        ),
    ]
