# Generated by Django 4.2.1 on 2024-03-07 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prompt_studio_core",
            "0007_remove_customtool_default_profile_and_more",
        ),
        ("prompt_profile_manager", "0006_alter_profilemanager_x2text"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemanager",
            name="is_default",
            field=models.BooleanField(
                db_comment="Default LLM Profile used in prompt", default=False
            ),
        ),
        migrations.AddField(
            model_name="profilemanager",
            name="is_summarize_llm",
            field=models.BooleanField(
                db_comment="Default LLM Profile used for summarizing",
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="profilemanager",
            name="prompt_studio_tool",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="prompt_studio_core.customtool",
            ),
        ),
    ]
