# Generated by Django 4.2.1 on 2024-03-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_profile_manager", "0007_profilemanager_is_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemanager",
            name="profile_name",
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name="profilemanager",
            constraint=models.UniqueConstraint(
                fields=("prompt_studio_tool", "profile_name"),
                name="unique_prompt_studio_tool_profile_name",
            ),
        ),
    ]
