# Generated by Django 4.2.1 on 2024-03-08 06:30

from typing import Any

from django.db import migrations
from prompt_studio.prompt_profile_manager.models import ProfileManager
from prompt_studio.prompt_studio.models import ToolStudioPrompt
from prompt_studio.prompt_studio_core.models import CustomTool


class Migration(migrations.Migration):
    dependencies = [
        (
            "prompt_profile_manager",
            "0007_profilemanager_is_default_and_more",
        ),
    ]

    def MigrateProfileManager(apps: Any, schema_editor: Any) -> None:
        # Iterate over prompt studio tools
        custom_tools = CustomTool.objects.all()
        for custom_tool in custom_tools:
            custom_prompts = ToolStudioPrompt.objects.filter(
                tool_id=custom_tool
            ).distinct("profile_manager")
            """Iterate over prompts inside specific tool and return the once
            which has distinct profile manager."""

            for index, custom_prompt in enumerate(custom_prompts):
                profile_manager = ProfileManager.objects.get(
                    pk=custom_prompt.profile_manager.profile_id
                )
                """Check this profile manager to see if the profile manager is
                tagged to any prompt tool If its none,  meaning profile manager
                created was global and before migration."""

                if not profile_manager.prompt_studio_tool:
                    # Copy Profile manager Id before replicating
                    profile_id = profile_manager.profile_id
                    # Replicate those profile manager
                    replicated_profile_manager = profile_manager
                    replicated_profile_manager.profile_id = None
                    replicated_profile_manager.profile_name = (
                        f"Profile_{index+1}"
                    )
                    """Attach the replicated profile manager to the
                    corresponding prompt tool."""
                    replicated_profile_manager.prompt_studio_tool = custom_tool
                    replicated_profile_manager.save()
                    """Custom prompts where the profile manager and tool
                    associated  replace it with replicated profile manager."""

                    ToolStudioPrompt.objects.filter(
                        profile_manager=profile_id, tool_id=custom_tool
                    ).update(profile_manager=replicated_profile_manager)

    operations = [
        migrations.RunPython(
            MigrateProfileManager, reverse_code=migrations.RunPython.noop
        ),
    ]
