# Generated by Django 4.2.1 on 2024-03-18 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prompt_studio_core",
            "0008_customtool_exclude_failed_customtool_monitor_llm",
        ),
        ("prompt_profile_manager", "0008_profilemanager_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemanager",
            name="prompt_studio_tool",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="prompt_studio_core.customtool",
            ),
        ),
    ]
