# Generated by Django 4.2.1 on 2024-03-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prompt_profile_manager",
            "0009_alter_profilemanager_prompt_studio_tool",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemanager",
            name="retrieval_strategy",
            field=models.TextField(
                blank=True,
                choices=[("simple", "Simple retrieval")],
                db_comment="Field to store the retrieval strategy for prompts",
            ),
        ),
        migrations.AlterField(
            model_name="profilemanager",
            name="similarity_top_k",
            field=models.IntegerField(
                blank=True,
                db_comment="Field to store number of top embeddings to take into context",
                null=True,
            ),
        ),
    ]
