# Generated by Django 4.2.1 on 2024-05-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prompt_profile_manager",
            "0010_alter_profilemanager_retrieval_strategy_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemanager",
            name="retrieval_strategy",
            field=models.TextField(
                blank=True,
                choices=[
                    ("simple", "Simple retrieval"),
                    ("subquestion", "Subquestion retrieval"),
                ],
                db_comment="Field to store the retrieval strategy for prompts",
            ),
        ),
    ]
