# Generated by Django 4.2.1 on 2024-06-10 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_studio_core", "0013_customtool_share_id"),
        ("prompt_profile_manager", "0011_alter_profilemanager_retrieval_strategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemanager",
            name="prompt_studio_tool",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_profilemanager",
                to="prompt_studio_core.customtool",
            ),
        ),
    ]
