# Generated by Django 4.2.1 on 2024-01-23 11:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("project_name", models.CharField(max_length=128, unique=True)),
                (
                    "settings",
                    models.JSONField(db_comment="Project settings", null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=490, null=True),
                ),
                (
                    "project_status",
                    models.TextField(blank=True, max_length=128, null=True),
                ),
                (
                    "project_identifier",
                    models.CharField(
                        choices=[
                            ("ETL", "ETL"),
                            ("TASK", "TASK"),
                            ("DEFAULT", "Default"),
                            ("APP", "App"),
                        ],
                        default="DEFAULT",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("id", "project_name"), name="unique_project_name"
            ),
        ),
    ]
