# Generated by Django 4.2.1 on 2025-08-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "connector_v2",
            "0004_remove_connectorinstance_unique_workflow_connector_and_more",
        ),
        ("endpoint_v2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowendpoint",
            name="connector_instance",
            field=models.ForeignKey(
                db_comment="Foreign key from ConnectorInstance model",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_endpoints",
                to="connector_v2.connectorinstance",
            ),
        ),
    ]
