# Generated by Django 4.2.1 on 2024-06-24 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sps_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPSDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(db_comment='Field to store document name', max_length=255)),
                ('index_status', models.CharField(choices=[('yet_to_start', 'Yet to Start'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], db_comment='Field to store index status', default='yet_to_start', max_length=20)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sps_project.spsproject')),
            ],
            options={
                'db_table': 'sps_document',
            },
        ),
        migrations.AddConstraint(
            model_name='spsdocument',
            constraint=models.UniqueConstraint(fields=('tool', 'document_name'), name='unique_document_name_per_project'),
        ),
    ]
