# Generated by Django 4.2.30 on 2026-06-19 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_v2", "0005_alter_platformkey_organization"),
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="organization",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_configuration",
                to="account_v2.organization",
            ),
        ),
    ]
