# Generated by Django 4.2.1 on 2024-01-20 08:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prompt_profile_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomTool",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tool_name", models.TextField(unique=True)),
                ("description", models.TextField()),
                (
                    "author",
                    models.TextField(
                        db_comment="Specific to the user who created the tool."
                    ),
                ),
                (
                    "icon",
                    models.TextField(
                        blank=True,
                        db_comment="Field to store             icon url for the custom tool.",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("JSON", "Output stored as JSON"),
                            ("YAML", "Output stored as YAML"),
                        ],
                        db_comment="Field to store the output format type.",
                    ),
                ),
                (
                    "log_id",
                    models.UUIDField(
                        db_comment="Field to store unique log_id for polling",
                        default=uuid.uuid4,
                    ),
                ),
                (
                    "preamble",
                    models.TextField(
                        blank=True, db_comment="Preamble to the prompts"
                    ),
                ),
                (
                    "postamble",
                    models.TextField(
                        blank=True,
                        db_comment="Appended as postable to prompts.",
                    ),
                ),
                (
                    "prompt_grammer",
                    models.JSONField(
                        blank=True,
                        db_comment="Synonymous words used in prompt",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_profile",
                        to="prompt_profile_manager.profilemanager",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
