# Generated by Django 4.2.1 on 2024-01-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtool",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="customtool",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
