# Generated by Django 4.2.1 on 2024-01-25 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_core", "0002_alter_customtool_output"),
        (
            "prompt_studio_core",
            "0002_remove_customtool_updated_at_customtool_modified_at",
        ),
    ]

    operations = []
