# Generated by Django 4.2.1 on 2024-02-27 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_profile_manager", "0006_alter_profilemanager_x2text"),
        ("prompt_studio_core", "0003_merge_20240125_1501"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="summarize_as_source",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customtool",
            name="summarize_context",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customtool",
            name="summarize_llm_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="summarize_llm_profile",
                to="prompt_profile_manager.profilemanager",
            ),
        ),
        migrations.AddField(
            model_name="customtool",
            name="summarize_prompt",
            field=models.TextField(
                blank=True, db_comment="Field to store the summarize prompt"
            ),
        ),
    ]
