# Generated by Django 4.2.1 on 2024-03-07 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "prompt_studio_core",
            "0006_alter_customtool_summarize_as_source_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtool",
            name="default_profile",
        ),
        migrations.RemoveField(
            model_name="customtool",
            name="summarize_llm_profile",
        ),
    ]
