# Generated by Django 4.2.1 on 2024-03-13 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adapter_processor", "0005_alter_adapterinstance_adapter_type"),
        ("prompt_studio_core", "0007_remove_customtool_default_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="exclude_failed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customtool",
            name="monitor_llm",
            field=models.ForeignKey(
                blank=True,
                db_comment="Field to store monitor llm",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="adapter_processor.adapterinstance",
            ),
        ),
    ]
