# Generated by Django 4.2.1 on 2024-03-15 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "prompt_studio_core",
            "0008_customtool_exclude_failed_customtool_monitor_llm",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="shared_users",
            field=models.ManyToManyField(
                related_name="shared_custom_tool", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
