# Generated by Django 4.2.1 on 2024-03-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prompt_studio_core",
            "0008_customtool_exclude_failed_customtool_monitor_llm",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="single_pass_extraction_mode",
            field=models.BooleanField(
                db_comment="Flag to enable or disable single pass extraction mode",
                default=True,
            ),
        ),
        migrations.AlterField(
            model_name="customtool",
            name="exclude_failed",
            field=models.BooleanField(
                db_comment="Flag to make the answer null if it is incorrect",
                default=True,
            ),
        ),
    ]
