# Generated by Django 4.2.1 on 2024-03-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prompt_studio_core",
            "0010_customtool_challenge_llm_customtool_enable_challenge_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customtool",
            name="postamble",
            field=models.TextField(
                blank=True,
                db_comment="Appended as postable to prompts.",
                default="Do not include any explanation in the reply. Only include the extracted information in the reply.",
            ),
        ),
        migrations.AlterField(
            model_name="customtool",
            name="preamble",
            field=models.TextField(
                blank=True,
                db_comment="Preamble to the prompts",
                default="Your ability to extract and summarize this context accurately is essential for effective analysis. Pay close attention to the context's language, structure, and any cross-references to ensure a comprehensive and precise extraction of information. Do not use prior knowledge or information from outside the context to answer the questions. Only use the information provided in the context to answer the questions.",
            ),
        ),
    ]
