# Generated by Django 4.2.1 on 2024-03-25 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "adapter_processor",
            "0007_remove_adapterinstance_is_default_userdefaultadapter",
        ),
        (
            "prompt_studio_core",
            "0011_alter_customtool_postamble_alter_customtool_preamble",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="shared_users",
            field=models.ManyToManyField(
                related_name="shared_custom_tool", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customtool",
            name="monitor_llm",
            field=models.ForeignKey(
                blank=True,
                db_comment="Field to store monitor llm",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="monitor_customtools",
                to="adapter_processor.adapterinstance",
            ),
        ),
    ]
