# Generated by Django 4.2.1 on 2024-05-30 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share_manager", "0001_initial"),
        ("prompt_studio_core", "0012_customtool_shared_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="share_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="share_linked_tool",
                to="share_manager.sharemanager",
            ),
        ),
    ]
