# Generated by Django 4.2.1 on 2024-06-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_studio_core", "0012_customtool_shared_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="enable_highlight",
            field=models.BooleanField(
                db_comment="Flag to enable or disable document highlighting",
                default=False,
            ),
        ),
    ]
