# Generated by Django 4.2.1 on 2024-07-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_studio_core", "0013_customtool_enable_highlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="tag",
            field=models.TextField(
                blank=True,
                db_comment="Appended as postable to prompts.",
                default="Initial Version",
                null=True,
            ),
        ),
    ]
