# Generated by Django 4.2.1 on 2024-06-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_studio_core", "0013_customtool_share_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="parent_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_parent_id",
                to="prompt_studio_core.customtool",
            ),
        ),
    ]
