# Generated by Django 4.2.1 on 2024-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_studio_core", "0014_customtool_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtool",
            name="tag",
        ),
        migrations.AddField(
            model_name="customtool",
            name="tag_id",
            field=models.TextField(
                blank=True,
                db_comment="Currently checked-in tag id",
                default=None,
                null=True,
            ),
        ),
    ]
