# Generated by Django 4.2.1 on 2025-01-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage_v2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage",
            name="run_id",
            field=models.UUIDField(
                blank=True, db_comment="Identifier for the run", null=True
            ),
        ),
    ]
