# Generated by Django 4.2.1 on 2025-04-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage_v2", "0002_alter_usage_run_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="usage",
            index=models.Index(
                fields=["execution_id"], name="usage_executi_4deb35_idx"
            ),
        ),
    ]
