# Generated by Django 4.2.1 on 2026-04-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usage_v2", "0003_usage_usage_executi_4deb35_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage",
            name="llm_usage_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extraction", "Extraction"),
                    ("challenge", "Challenge"),
                    ("summarize", "Summarize"),
                    ("lookup", "Lookup"),
                ],
                db_comment="Reason for LLM usage. Empty if usage_type is 'embedding'. ",
                max_length=255,
                null=True,
            ),
        ),
    ]
