# Generated by Django 4.2.1 on 2026-04-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usage_v2", "0005_usage_reason_ref_created_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage",
            name="llm_usage_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extraction", "Extraction"),
                    ("challenge", "Challenge"),
                    ("summarize", "Summarize"),
                    ("lookup", "Lookup"),
                ],
                db_comment="Reason for LLM usage. Empty if usage_type is 'embedding'. ",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usage",
            name="reference_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prompt_key", "Prompt Key"),
                    ("lookup_version", "Lookup Version"),
                ],
                db_comment="Discriminator for reference_id. OSS values: 'prompt_key'. NULL when reference_id is NULL.",
                max_length=64,
                null=True,
            ),
        ),
    ]
