# Generated by Django 4.2.1 on 2026-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usage_v2", "0005_usage_reason_ref_created_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUCCESS", "Success"),
                    ("ERROR", "Error"),
                    ("SKIPPED", "Skipped"),
                ],
                db_comment="Operation outcome: SUCCESS, ERROR, or SKIPPED",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="usage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("reference_id__isnull", True), ("reference_type__isnull", True)
                    ),
                    models.Q(
                        ("reference_id__isnull", False), ("reference_type__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="usage_reference_pair_consistent",
            ),
        ),
    ]
