# mypy: ignore-errors
# Generated by Django 4.2.1 on 2023-07-18 10:40

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_public_tenant_and_domain(apps, schema_editor):
    Organization = apps.get_model("account", "Organization")

    # public tenant
    tenant = Organization(
        name="public",
        display_name="public",
        organization_id="public",
        schema_name="public",
    )
    tenant.save()

    User = apps.get_model("account", "User")
    # public User admin
    user = User(
        username="admin",
        email="admin@zipstack.com",
        is_superuser=True,
        is_staff=True,
        password=make_password("ascon"),
    )
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_public_tenant_and_domain),
    ]
