# Generated by Django 4.2.1 on 2024-02-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_platformkey_key_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptionSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
