# Generated by Django 4.2.1 on 2024-03-04 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_encryptionsecret"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EncryptionSecret",
        ),
    ]
