# Generated by Django 4.2.1 on 2024-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_delete_encryptionsecret"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="allowed_token_limit",
            field=models.IntegerField(
                db_comment="token limit set in case of frition less onbaoarded org",
                default=-1,
            ),
        ),
    ]
