# Generated by Django 4.2.1 on 2024-08-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_usage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageusage",
            name="pages_processed",
            field=models.IntegerField(db_comment="Number of pages which got processed"),
        ),
    ]
