# Generated by Django 4.2.1 on 2024-12-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_studio_v2", "0002_alter_toolstudioprompt_enforce_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolstudioprompt",
            name="required",
            field=models.BooleanField(default=False),
        ),
    ]
