# Generated by Django 4.2.1 on 2025-04-24 11:31

from django.db import migrations

def forward_enforce_type_updates(apps, schema_editor):
    prompt = apps.get_model("prompt_studio_v2", "ToolStudioPrompt")
    
    # line-item -> json
    prompt.objects.filter(enforce_type="line-item").update(enforce_type="json")
    
    # table or record -> line-item
    prompt.objects.filter(enforce_type__in=["table", "record"]).update(enforce_type="line-item")


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_studio_v2", "0006_alter_toolstudioprompt_enforce_type"),
    ]

    operations = [
        migrations.RunPython(forward_enforce_type_updates, migrations.RunPython.noop),
    ]
