# Generated by Django 4.2.1 on 2025-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_v2", "0012_alter_toolstudioprompt_enforce_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolstudioprompt",
            name="enable_postprocessing_webhook",
            field=models.BooleanField(
                db_comment="Enable postprocessing webhook for JSON responses",
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="toolstudioprompt",
            name="postprocessing_webhook_url",
            field=models.TextField(
                blank=True,
                db_comment="URL endpoint for postprocessing webhook",
                null=True,
            ),
        ),
    ]
