# Generated by Django 4.2.1 on 2025-01-21 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lookup", "0001_initial"),
        (
            "prompt_studio_v2",
            "0013_toolstudioprompt_enable_postprocessing_webhook_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="toolstudioprompt",
            name="lookup_project",
            field=models.ForeignKey(
                blank=True,
                db_comment="Lookup project for this prompt's enrichment. "
                "Must be linked at project level via PromptStudioLookupLink.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_prompts",
                to="lookup.lookupproject",
            ),
        ),
    ]
