# Generated by Django 4.2.1 on 2024-03-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_document_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="documentmanager",
            constraint=models.UniqueConstraint(
                fields=("document_name", "tool"), name="unique_document_name_tool"
            ),
        ),
    ]
