# Generated by Django 4.2.1 on 2024-07-02 12:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workflow", "0005_executionlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppDeployment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "app_display_name",
                    models.CharField(
                        db_comment="User-given name for the Application.",
                        default="api deployment",
                        max_length=30,
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        db_comment="Short name for the APP deployment.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_comment="User-given description for the Application",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Flag indicating status is active or not.",
                        default=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_deployment_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_deployment_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_users",
                    models.ManyToManyField(
                        related_name="shared_app_deployment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        db_comment="Foreign key reference to Workflow model.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.workflow",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndexedDocuments",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        db_comment="Name of indexed file", max_length=64, null=True
                    ),
                ),
                (
                    "document_id",
                    models.CharField(
                        db_comment="Doc id supplied from multi doc chat",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "app_deployment",
                    models.ForeignKey(
                        db_comment="Foreign key reference to App Deployment  model.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indexed_document_app",
                        to="app_deployment.appdeployment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
