from django.db import models
from django.utils import timezone


class PgQueueMessage(models.Model):
    """Bespoke extension-free queue table (``SKIP LOCKED`` + visibility timeout).

    The table and its dequeue index are Django-managed (generated by
    ``makemigrations``, migration 0001). Two things Django 4.2 cannot
    express are added by hand in migration 0002 via ``RunSQL`` — and only
    those: (a) DB-level ``DEFAULT now()`` / ``0`` on the columns the raw-SQL
    producer omits (``db_default`` needs Django 5.0+), and (b) the
    ``pg_queue_read`` claim function (no model concept for SQL functions).
    See UN-3533 (extension-free decision).
    """

    msg_id = models.BigAutoField(primary_key=True)
    queue_name = models.TextField()
    message = models.JSONField()
    # "" = no org (leaf tasks); the fair-admission query (a later phase)
    # uses it for the coupled pipeline. Empty string rather than NULL —
    # a string field shouldn't have two "no data" values (Django S6553).
    org_id = models.TextField(blank=True, default="")
    # Python-level defaults so ORM ``.create()`` works without these; the
    # raw-SQL client relies on the DB-level defaults added in migration 0002.
    enqueued_at = models.DateTimeField(default=timezone.now)
    vt = models.DateTimeField(default=timezone.now)  # visibility timeout
    read_ct = models.IntegerField(default=0)

    class Meta:
        db_table = "pg_queue_message"
        indexes = [
            models.Index(
                fields=["queue_name", "vt", "msg_id"],
                name="pg_queue_message_dequeue_idx",
            )
        ]
