# Generated by Django 4.2.1 on 2024-06-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0002_alter_usage_adapter_instance_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usage",
            name="llm_usage_reason",
            field=models.CharField(
                blank=True,
                db_comment=(
                    "Reason for LLM usage, e.g., 'extraction', 'challenge' or 'summarize'. "
                    "Empty if usage_type is 'embedding'."
                ),
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usage",
            name="usage_type",
            field=models.CharField(
                db_comment="Type of usage, either 'llm' or 'embedding'", max_length=255
            ),
        ),
    ]
