# Generated by Django 4.2.1 on 2024-03-09 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "prompt_studio_document_manager",
            "0002_documentmanager_unique_document_name_tool",
        ),
        ("prompt_profile_manager", "0006_alter_profilemanager_x2text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexManager",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "index_manager_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_index_id",
                    models.CharField(
                        blank=True,
                        db_comment="Field to store the raw index id",
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "summarize_index_id",
                    models.CharField(
                        blank=True,
                        db_comment="Field to store the summarize index id",
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "index_ids_history",
                    models.JSONField(db_comment="List of index ids", default=list),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_index_manager_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_manager",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_manager_linked_document",
                        to="prompt_studio_document_manager.documentmanager",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_index_manager_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_manager",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="index_manager_linked_raw_llm_profile",
                        to="prompt_profile_manager.profilemanager",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
