# Generated by Django 4.2.1 on 2024-03-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_profile_manager", "0006_alter_profilemanager_x2text"),
        (
            "prompt_studio_document_manager",
            "0002_documentmanager_unique_document_name_tool",
        ),
        ("prompt_studio_index_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexmanager",
            name="document_manager",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="index_manager_linked_document",
                to="prompt_studio_document_manager.documentmanager",
            ),
        ),
        migrations.AlterField(
            model_name="indexmanager",
            name="raw_index_id",
            field=models.CharField(
                blank=True,
                db_comment="Field to store the raw index id",
                editable=False,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="indexmanager",
            name="raw_llm_profile",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="index_manager_linked_raw_llm_profile",
                to="prompt_profile_manager.profilemanager",
            ),
        ),
        migrations.AlterField(
            model_name="indexmanager",
            name="summarize_index_id",
            field=models.CharField(
                blank=True,
                db_comment="Field to store the summarize index id",
                editable=False,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="indexmanager",
            name="summarize_llm_profile",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="index_manager_linked_summarize_llm_profile",
                to="prompt_profile_manager.profilemanager",
            ),
        ),
    ]
