# Generated by Django 4.2.1 on 2024-03-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_index_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="indexmanager",
            constraint=models.UniqueConstraint(
                fields=("document_manager", "profile_manager"),
                name="unique_document_manager_profile_manager",
            ),
        ),
    ]
