# Generated by Django 4.2.1 on 2025-09-02 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_v2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apideployment",
            name="shared_to_org",
            field=models.BooleanField(
                db_comment="Whether this API deployment is shared with the entire organization",
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="apideployment",
            name="shared_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_api_deployments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
