# Generated by Django 4.2.1 on 2025-11-08 12:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_v2", "0002_user_auth_provider"),
        ("api_v2", "0002_apideployment_shared_to_org_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationRateLimit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "concurrent_request_limit",
                    models.IntegerField(
                        db_comment="Maximum number of concurrent API deployment requests allowed for this organization",
                        default=5,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_v2.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Rate Limit",
                "verbose_name_plural": "Organization Rate Limits",
                "db_table": "organization_rate_limit",
            },
        ),
        migrations.AddConstraint(
            model_name="organizationratelimit",
            constraint=models.UniqueConstraint(
                fields=("organization",), name="unique_org_rate_limit"
            ),
        ),
    ]
