# Generated by Django 4.2.1 on 2025-07-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adapter_processor_v2", "0001_initial"),
        ("prompt_studio_core_v2", "0002_add_summarize_llm_adapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customtool",
            name="summarize_llm_adapter",
            field=models.ForeignKey(
                blank=True,
                db_comment="Field to store the LLM adapter for summarization",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="summarize_enabled_custom_tools",
                to="adapter_processor_v2.adapterinstance",
            ),
        ),
    ]
