# Generated by Django 4.2.1 on 2025-10-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_core_v2", "0003_alter_customtool_summarize_llm_adapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="shared_to_org",
            field=models.BooleanField(
                db_comment="Flag to share this custom tool with all users in the organization",
                default=False,
            ),
        ),
    ]
