# Generated by Django 4.2.1 on 2025-12-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_core_v2", "0005_customtool_enable_word_confidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="custom_data",
            field=models.JSONField(
                blank=True,
                db_comment="Custom data for variable replacement in prompts using {{custom_data.key}} syntax",
                null=True,
            ),
        ),
    ]
