# Generated by Django 4.2.1 on 2026-02-23 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prompt_studio_core_v2", "0006_add_custom_data_to_customtool"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="co_owners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users with full ownership privileges",
                related_name="co_owned_custom_tools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
