# Generated by Django 4.2.1 on 2026-04-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_core_v2", "0006_add_custom_data_to_customtool"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="last_exported_at",
            field=models.DateTimeField(
                blank=True,
                db_comment="Timestamp of the last successful export; NULL if never exported since the field was introduced.",
                null=True,
            ),
        ),
    ]
