# Generated by Django 4.2.1 on 2026-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_account_v2", "0002_organization_group_group_membership"),
        ("prompt_studio_core_v2", "0007_customtool_last_exported_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="shared_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_custom_tools",
                to="tenant_account_v2.organizationgroup",
            ),
        ),
    ]
