# Generated by Django 4.2.30 on 2026-07-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_core_v2", "0009_absorb_shared_users"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customtool",
            index=models.Index(
                fields=["organization", "-modified_at"], name="custtool_org_modified_idx"
            ),
        ),
    ]
