# Generated by Django 4.2.1 on 2025-01-08 21:08

import json

from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations


def migrate_adapter_data(apps, schema_editor):
    AdapterInstance = apps.get_model("adapter_processor_v2", "AdapterInstance")

    old_adapter_id = "llmwhisperer|0a1647f0-f65f-410d-843b-3d979c78350e"
    new_adapter_id = "llmwhisperer|a5e6b8af-3e1f-4a80-b006-d017e8e67f93"

    for adapter in AdapterInstance.objects.all():

        # Deserialize adapter_metadata_b if it exists
        encryption_secret: str = settings.ENCRYPTION_KEY
        f: Fernet = Fernet(encryption_secret.encode("utf-8"))
        if adapter.adapter_metadata_b:

            metadata = json.loads(
                f.decrypt(bytes(adapter.adapter_metadata_b).decode("utf-8"))
            )
        else:
            metadata = {}

        # Add version in adapter_metadata_b
        if "version" not in metadata:
            if adapter.adapter_id == old_adapter_id:
                metadata["version"] = "v1"
            else:
                metadata["version"] = "v2"

        # Serialize and save updated metadata

        adapter.adapter_metadata_b = f.encrypt(json.dumps(metadata).encode("utf-8"))

        if adapter.adapter_id == old_adapter_id:
            adapter.adapter_id = new_adapter_id

        adapter.save()


class Migration(migrations.Migration):

    dependencies = [
        ("adapter_processor_v2", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_adapter_data),
    ]
