# Generated by Django 4.2.1 on 2026-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_account_v2", "0002_organization_group_group_membership"),
        ("adapter_processor_v2", "0003_mark_deprecated_adapters"),
    ]

    operations = [
        migrations.AddField(
            model_name="adapterinstance",
            name="shared_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_adapter_instances",
                to="tenant_account_v2.organizationgroup",
            ),
        ),
    ]
