# Generated by Django 4.2.30 on 2026-07-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adapter_processor_v2", "0005_absorb_shared_users"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="adapterinstance",
            index=models.Index(
                fields=["organization", "-modified_at"], name="adapter_org_modified_idx"
            ),
        ),
    ]
