class LogType:
    LOG = "LOG"
    UPDATE = "UPDATE"
    COST = "COST"
    RESULT = "RESULT"
    SINGLE_STEP = "SINGLE_STEP_MESSAGE"


class LogLevel:
    ERROR = "ERROR"
    WARN = "WARN"
    INFO = "INFO"
    DEBUG = "DEBUG"


class ToolKey:
    TOOL_INSTANCE_ID = "tool_instance_id"


class Env:
    TOOL_CONTAINER_NETWORK = "TOOL_CONTAINER_NETWORK"
    TOOL_CONTAINER_LABELS = "TOOL_CONTAINER_LABELS"
    WORKFLOW_DATA_DIR = "WORKFLOW_DATA_DIR"
    EXECUTION_RUN_DATA_FOLDER = "EXECUTION_RUN_DATA_FOLDER"
    EXECUTION_RUN_DATA_FOLDER_PREFIX = "EXECUTION_RUN_DATA_FOLDER_PREFIX"
    TOOL_DATA_DIR = "TOOL_DATA_DIR"
    PRIVATE_REGISTRY_CREDENTIAL_PATH = "PRIVATE_REGISTRY_CREDENTIAL_PATH"
    PRIVATE_REGISTRY_USERNAME = "PRIVATE_REGISTRY_USERNAME"
    PRIVATE_REGISTRY_URL = "PRIVATE_REGISTRY_URL"
    LOG_LEVEL = "LOG_LEVEL"
    REMOVE_CONTAINER_ON_EXIT = "REMOVE_CONTAINER_ON_EXIT"
    WORKFLOW_EXECUTION_DIR_PREFIX = "WORKFLOW_EXECUTION_DIR_PREFIX"
    WORKFLOW_EXECUTION_FILE_STORAGE_CREDENTIALS = (
        "WORKFLOW_EXECUTION_FILE_STORAGE_CREDENTIALS"
    )
    EXECUTION_DATA_DIR = "EXECUTION_DATA_DIR"
    FLIPT_SERVICE_AVAILABLE = "FLIPT_SERVICE_AVAILABLE"


class FeatureFlag:
    """Temporary feature flags."""

    REMOTE_FILE_STORAGE = "remote_file_storage"
