# Generated by Django 4.2.1 on 2024-03-17 17:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0002_remove_workflow_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="execution_log_id",
            field=models.CharField(
                db_comment="Execution log events Id", default="", editable=False
            ),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="project_settings_id",
            field=models.UUIDField(
                db_comment="Id of project settings used while execution",
                default=uuid.uuid4,
                editable=False,
            ),
        ),
    ]
