# Generated by Django 4.2.1 on 2024-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0002_remove_workflow_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="execution_log_id",
            field=models.CharField(
                db_comment="Execution log events Id", default="", editable=False
            ),
        ),
    ]
