# Generated by Django 4.2.1 on 2024-04-22 06:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0003_workflowexecution_execution_log_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "execution_id",
                    models.UUIDField(db_comment="Execution ID", editable=False),
                ),
                ("data", models.JSONField()),
                ("event_time", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
