# Generated by Django 4.2.1 on 2024-06-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0005_executionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="filehistory",
            name="meta_data",
            field=models.TextField(blank=True, db_comment="MetaData from execution"),
        ),
    ]
