# Generated by Django 4.2.1 on 2024-09-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0006_filehistory_meta_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="prompt_name",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="prompt_text",
        ),
    ]
