# Generated by Django 4.2.1 on 2024-03-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipeline",
            name="last_run_status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("INPROGRESS", "Inprogress"),
                    ("YET_TO_START", "Yet to start"),
                    ("RESTARTING", "Restarting"),
                    ("PAUSED", "Paused"),
                ],
                default="YET_TO_START",
            ),
        ),
    ]
