# Generated by Django 4.2.1 on 2024-03-05 22:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_alter_pipeline_last_run_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineLogs",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_comment="Unique identifier for the Pipeline Logs.",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("log_id", models.CharField(max_length=255)),
                ("started_at", models.CharField(max_length=255)),
                ("completed_at", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("triggered_by", models.CharField(max_length=255)),
                ("log_text", models.JSONField()),
                (
                    "Pipeline",
                    models.ForeignKey(
                        db_comment="Foreign key reference to the Pipeline model.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pipeline.pipeline",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
