# Generated by Django 4.2.1 on 2024-07-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_alter_pipeline_last_run_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipeline",
            name="active",
            field=models.BooleanField(
                db_comment="Indicates whether the pipeline is active", default=False
            ),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="cron_string",
            field=models.TextField(
                db_comment="UNIX cron string", max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="scheduled",
            field=models.BooleanField(
                db_comment="Indicates whether the pipeline is scheduled", default=False
            ),
        ),
    ]
