# Generated by Django 4.2.1 on 2024-08-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0003_alter_pipeline_active_alter_pipeline_cron_string_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipeline",
            name="cron_string",
            field=models.TextField(
                blank=True, db_comment="UNIX cron string", max_length=256, null=True
            ),
        ),
    ]
