# Generated by Django 4.2.1 on 2024-01-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_deployment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appdeployment",
            name="subdomain",
            field=models.CharField(
                db_comment="User-given name for the Application.",
                max_length=30,
                unique=True,
            ),
        ),
    ]
