# Generated by Django 4.2.1 on 2024-01-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_deployment", "0002_alter_appdeployment_subdomain"),
    ]

    operations = [
        migrations.AddField(
            model_name="appdeployment",
            name="dns_domain",
            field=models.CharField(
                db_comment="Main domain under which the subdomain is added.",
                default="NA",
                editable=False,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appdeployment",
            name="dns_provider",
            field=models.CharField(
                choices=[
                    ("LOCALHOST", "Localhost DNS"),
                    ("CLOUDFLARE", "Cloudflare DNS"),
                ],
                db_comment="DNS Provider which was used for configuration.",
                default="NA",
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appdeployment",
            name="dns_top_level_domain",
            field=models.CharField(
                db_comment="Top domain like com, io etc.",
                default="NA",
                editable=False,
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
