# Generated by Django 4.2.1 on 2024-01-16 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_deployment",
            "0003_appdeployment_dns_domain_appdeployment_dns_provider_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appdeployment",
            name="dns_domain",
            field=models.CharField(
                db_comment="Main domain under which the subdomain is added.",
                editable=False,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid domain name.",
                        regex="^[a-zA-Z0-9.-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="appdeployment",
            name="dns_top_level_domain",
            field=models.CharField(
                db_comment="Top domain like com, io etc.",
                editable=False,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid domain name.",
                        regex="^[a-zA-Z0-9.-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="appdeployment",
            name="subdomain",
            field=models.CharField(
                db_comment="User-given name for the Application.",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid domain name.",
                        regex="^[a-zA-Z0-9.-]+$",
                    )
                ],
            ),
        ),
    ]
