# Generated by Django 4.2.30 on 2026-06-19 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_v2", "0005_alter_platformkey_organization"),
        ("notification_v2", "0002_notification_batching"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationbuffer",
            name="organization",
            field=models.ForeignKey(
                db_comment="Tenant scope. Mandatory grouping key — prevents cross-tenant leakage at flush time.",
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_buffer_rows",
                to="account_v2.organization",
            ),
        ),
    ]
