# Generated by Django 4.2.1 on 2024-06-26 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_v2", "0001_initial"),
        ("tenant_account_v2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmember",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_comment="Foreign key reference to the Organization model.",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_v2.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_user",
                to="account_v2.user",
            ),
        ),
    ]
