# Generated by Django 4.2.30 on 2026-06-19 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_v2", "0005_alter_platformkey_organization"),
        ("tenant_account_v2", "0003_resource_group_share"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationgroup",
            name="organization",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="account_v2.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_comment="Foreign key reference to the Organization model.",
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_v2.organization",
            ),
        ),
        migrations.AlterField(
            model_name="resourcegroupshare",
            name="organization",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_group_shares",
                to="account_v2.organization",
            ),
        ),
    ]
