# Generated by Django 4.2.1 on 2026-07-06 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("account_v2", "0005_alter_platformkey_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenant_account_v2", "0004_alter_organizationgroup_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("viewer", "Viewer")],
                        default="viewer",
                        max_length=16,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_memberships",
                        to="account_v2.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Membership",
                "verbose_name_plural": "Resource Memberships",
                "db_table": "resource_membership",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "role"],
                        name="resource_me_content_624443_idx",
                    ),
                    models.Index(
                        fields=["organization", "user"],
                        name="resource_me_organiz_379987_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="resourcemembership",
            constraint=models.UniqueConstraint(
                fields=("user", "content_type", "object_id"),
                name="uniq_resource_membership",
            ),
        ),
    ]
