# Generated by Django 4.2.1 on 2025-01-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_v2", "0002_user_auth_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deprecated",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Marks old user records when OAuth user changes email",
            ),
        ),
    ]
