# Generated by Django 4.2.1 on 2026-03-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_v2", "0003_user_is_deprecated"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_service_account",
            field=models.BooleanField(
                db_comment="True for service accounts (e.g. platform API key bearer auth sessions)",
                default=False,
            ),
        ),
    ]
