# Generated by Django 4.2.1 on 2026-05-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_v2", "0004_user_is_service_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="idp_group_allowlist",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Allowed external_id values or fnmatch glob patterns for IdP group import. Matching is case-insensitive.",
            ),
        ),
    ]
