# Generated by Django 4.2.30 on 2026-06-19 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_v2", "0004_user_is_service_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformkey",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platform_keys",
                to="account_v2.organization",
            ),
        ),
    ]
