# Generated by Django 4.2.1 on 2024-01-23 11:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdapterInstance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_comment="Unique identifier for the Adapter Instance",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "adapter_name",
                    models.TextField(
                        db_comment="Name of the Adapter Instance",
                        max_length=128,
                    ),
                ),
                (
                    "adapter_id",
                    models.CharField(
                        db_comment="Unique identifier of the Adapter",
                        default="",
                        max_length=128,
                    ),
                ),
                (
                    "adapter_metadata",
                    models.JSONField(
                        db_column="adapter_metadata",
                        db_comment="JSON adapter metadata submitted by the user",
                        default=dict,
                    ),
                ),
                (
                    "adapter_type",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "UNKNOWN"),
                            ("LLM", "LLM"),
                            ("EMBEDDING", "EMBEDDING"),
                            ("VECTOR_DB", "VECTOR_DB"),
                        ],
                        db_comment="Type of adapter LLM/EMBEDDING/VECTOR_DB",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Is the adapter instance currently being used",
                        default=False,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_comment="Is the adapter instance default",
                        default=False,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_adapters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_adapters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "adapter_adapterinstance",
                "verbose_name_plural": "adapter_adapterinstance",
                "db_table": "adapter_adapterinstance",
            },
        ),
    ]
