# Generated by Django 4.2.1 on 2024-01-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adapter_processor", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="adapterinstance",
            constraint=models.UniqueConstraint(
                fields=("adapter_name", "adapter_type"), name="unique_adapter"
            ),
        ),
    ]
