# Generated by Django 4.2.1 on 2024-02-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adapter_processor", "0003_adapterinstance_adapter_metadata_b"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adapterinstance",
            name="adapter_type",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "UNKNOWN"),
                    ("LLM", "LLM"),
                    ("EMBEDDING", "EMBEDDING"),
                    ("VECTOR_DB", "VECTOR_DB"),
                    ("X2TEXT", "X2TEXT"),
                ],
                db_comment="Type of adapter LLM/EMBEDDING/VECTOR_DB",
            ),
        ),
    ]
