# Generated by Django 4.2.1 on 2024-03-11 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adapter_processor", "0005_alter_adapterinstance_adapter_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="adapterinstance",
            name="shared_users",
            field=models.ManyToManyField(
                related_name="shared_adapters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
