# Generated by Django 4.2.1 on 2024-03-12 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adapter_processor", "0006_adapterinstance_shared_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adapterinstance",
            name="is_default",
        ),
        migrations.CreateModel(
            name="UserDefaultAdapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "default_embedding_adapter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_embedding_adapter",
                        to="adapter_processor.adapterinstance",
                    ),
                ),
                (
                    "default_llm_adapter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_llm_adapter",
                        to="adapter_processor.adapterinstance",
                    ),
                ),
                (
                    "default_vector_db_adapter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_vector_db_adapter",
                        to="adapter_processor.adapterinstance",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
