# Generated by Django 4.2.1 on 2024-03-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "adapter_processor",
            "0007_remove_adapterinstance_is_default_userdefaultadapter",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userdefaultadapter",
            name="default_x2text_adapter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_x2text_adapter",
                to="adapter_processor.adapterinstance",
            ),
        ),
    ]
