# Generated by Django 4.2.1 on 2024-04-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "adapter_processor",
            "0007_remove_adapterinstance_is_default_userdefaultadapter",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="adapterinstance",
            name="is_friction_less",
            field=models.BooleanField(
                db_comment="Does the adapter created through frictionless onbaording",
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="adapterinstance",
            name="shared_to_org",
            field=models.BooleanField(
                db_comment="Is the adapter shared to enitire org", default=False
            ),
        ),
        migrations.AlterField(
            model_name="adapterinstance",
            name="is_active",
            field=models.BooleanField(
                db_comment="Is the adapter instance currently being used", default=True
            ),
        ),
    ]
