# Generated by Django 4.2.1 on 2024-04-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adapter_processor", "0008_adapterinstance_shared_to_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="adapterinstance",
            name="is_friction_less",
            field=models.BooleanField(
                db_comment="Does the adapter created through frictionless onbaording",
                default=False,
            ),
        ),
    ]
