# Generated by Django 4.2.1 on 2024-06-27 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sps_prompt', '0001_initial'),
        ('sps_project', '0001_initial'),
        ('sps_document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPSPromptOutput',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('prompt_output_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output', models.CharField(blank=True, db_comment='Field to store output', null=True)),
                ('document_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_outputs', to='sps_document.spsdocument')),
                ('prompt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_outputs', to='sps_prompt.spsprompt')),
                ('tool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_outputs', to='sps_project.spsproject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='spspromptoutput',
            constraint=models.UniqueConstraint(fields=('prompt_id', 'document_manager', 'tool_id'), name='unique_sps_prompt_output'),
        ),
    ]
