# Generated by Django 4.2.1 on 2024-01-16 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_transcript", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chattranscript",
            old_name="chat_histrory",
            new_name="chat_history",
        ),
    ]
