# Generated by Django 4.2.1 on 2024-01-17 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "chat_transcript",
            "0002_rename_chat_histrory_chattranscript_chat_history",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="chattranscript",
            old_name="question",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="chattranscript",
            name="answer",
        ),
        migrations.AddField(
            model_name="chattranscript",
            name="message_type",
            field=models.CharField(
                choices=[("question", "QUESTION"), ("answer", "ANSWER")],
                db_comment="Type of message question/answer",
                default="QUESTION",
            ),
        ),
        migrations.AddField(
            model_name="chattranscript",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="chat_transcript.chattranscript",
            ),
        ),
        migrations.AddField(
            model_name="chattranscript",
            name="role",
            field=models.CharField(
                choices=[("user", "USER"), ("assistant", "ASSISTANT")],
                db_comment="Role",
            ),
        ),
    ]
