# Generated by Django 4.2.1 on 2024-01-29 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "chat_transcript",
            "0003_rename_question_chattranscript_message_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chattranscript",
            name="message_type",
        ),
    ]
