# Generated by Django 4.2.1 on 2024-01-29 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_history", "0001_initial"),
        ("chat_transcript", "0004_remove_chattranscript_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chattranscript",
            name="chat_history",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_history_transcript",
                to="chat_history.chathistory",
            ),
        ),
        migrations.AlterField(
            model_name="chattranscript",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="chat_transcript.chattranscript",
            ),
        ),
        migrations.AlterField(
            model_name="chattranscript",
            name="role",
            field=models.CharField(
                choices=[
                    ("system", "SYSTEM"),
                    ("user", "USER"),
                    ("assistant", "ASSISTANT"),
                    ("function", "FUNCTION"),
                    ("tool", "TOOL"),
                ],
                db_comment="Role of the messenger.",
                editable=False,
            ),
        ),
    ]
