# Generated by Django 4.2.1 on 2024-06-19 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sps_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPSPrompt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_key', models.CharField(db_comment='Field to store prompt key', max_length=255)),
                ('prompt', models.TextField(db_comment='Field to store prompt')),
                ('sps_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='sps_project.spsproject')),
            ],
            options={
                'db_table': 'sps_prompt',
            },
        ),
        migrations.AddConstraint(
            model_name='spsprompt',
            constraint=models.UniqueConstraint(fields=('sps_project_id', 'prompt_key'), name='unique_prompt_key_per_project'),
        ),
    ]
