"""Environment Variable Names

Environment variable names for worker configuration.
"""


class EnvVars:
    """Environment variable names for configuration."""

    # Worker identification
    WORKER_NAME = "WORKER_NAME"
    WORKER_VERSION = "WORKER_VERSION"
    WORKER_INSTANCE_ID = "HOSTNAME"

    # Celery configuration
    CELERY_BROKER_BASE_URL = "CELERY_BROKER_BASE_URL"
    CELERY_BROKER_USER = "CELERY_BROKER_USER"
    CELERY_BROKER_PASS = "CELERY_BROKER_PASS"

    # Celery backend database
    CELERY_BACKEND_DB_HOST = "CELERY_BACKEND_DB_HOST"
    CELERY_BACKEND_DB_PORT = "CELERY_BACKEND_DB_PORT"
    CELERY_BACKEND_DB_NAME = "CELERY_BACKEND_DB_NAME"
    CELERY_BACKEND_DB_USER = "CELERY_BACKEND_DB_USER"
    CELERY_BACKEND_DB_PASSWORD = "CELERY_BACKEND_DB_PASSWORD"
    CELERY_BACKEND_DB_SCHEMA = "CELERY_BACKEND_DB_SCHEMA"

    # Redis cache configuration
    CACHE_REDIS_ENABLED = "CACHE_REDIS_ENABLED"
    CACHE_REDIS_HOST = "CACHE_REDIS_HOST"
    CACHE_REDIS_PORT = "CACHE_REDIS_PORT"
    CACHE_REDIS_DB = "CACHE_REDIS_DB"
    CACHE_REDIS_PASSWORD = "CACHE_REDIS_PASSWORD"  # gitleaks:allow
    CACHE_REDIS_USERNAME = "CACHE_REDIS_USERNAME"
    CACHE_REDIS_SSL = "CACHE_REDIS_SSL"

    # Internal API configuration
    INTERNAL_API_BASE_URL = "INTERNAL_API_BASE_URL"
    DJANGO_APP_BACKEND_URL = "DJANGO_APP_BACKEND_URL"
    INTERNAL_SERVICE_API_KEY = "INTERNAL_SERVICE_API_KEY"

    # Performance settings
    MAX_CONCURRENT_TASKS = "MAX_CONCURRENT_TASKS"
    TASK_TIMEOUT = "TASK_TIMEOUT"
    MAX_PARALLEL_FILE_BATCHES = "MAX_PARALLEL_FILE_BATCHES"

    # Monitoring settings
    ENABLE_METRICS = "ENABLE_METRICS"
    ENABLE_HEALTH_SERVER = "ENABLE_HEALTH_SERVER"
    METRICS_PORT = "METRICS_PORT"

    # Logging configuration
    LOG_LEVEL = "LOG_LEVEL"
    LOG_FORMAT = "LOG_FORMAT"
    LOG_FILE = "LOG_FILE"
