# Generated by Django 4.2.1 on 2024-11-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_v2", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="llm_response",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="prompt_name",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="prompt_text",
        ),
    ]
