# Generated by Django 4.2.1 on 2025-01-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("workflow_v2", "0004_executionlog_file_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="workflow_executions", to="tags.tag"
            ),
        ),
    ]
