# Generated by Django 4.2.1 on 2025-02-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_v2", "0007_update_execution_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="total_files",
            field=models.PositiveIntegerField(
                db_comment="Number of files to process",
                default=0,
                verbose_name="Total files",
            ),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="result_acknowledged",
            field=models.BooleanField(
                db_comment="To track if result is acknowledged by user - used mainly by API deployments",
                default=False,
            ),
        ),
    ]
