# Generated by Django 4.2.1 on 2025-03-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_v2", "0009_update_total_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filehistory",
            name="status",
            field=models.TextField(
                choices=[
                    ("PENDING", "Pending"),
                    ("EXECUTING", "Executing"),
                    ("COMPLETED", "Completed"),
                    ("STOPPED", "Stopped"),
                    ("ERROR", "Error"),
                ],
                db_comment="Latest status of execution",
            ),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("EXECUTING", "Executing"),
                    ("COMPLETED", "Completed"),
                    ("STOPPED", "Stopped"),
                    ("ERROR", "Error"),
                ],
                db_comment="Current status of the execution",
            ),
        ),
    ]
