# Generated by Django 4.2.1 on 2025-04-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_v2", "0010_executionlog_wf_execution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="related_workflow",
            field=models.ForeignKey(
                db_column="related_wf_id",
                db_comment="Workflow to be executed",
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="workflow_v2.workflow",
            ),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="workflow_id",
            field=models.UUIDField(
                db_comment="ID of workflow being executed (deprecated)",
                editable=False,
                null=True,
            ),
        ),
    ]
