# Generated by Django 4.2.1 on 2025-03-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_v2", "0010_alter_filehistory_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionlog",
            name="wf_execution",
            field=models.ForeignKey(
                blank=True,
                db_comment="Foreign key from WorkflowExecution model",
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution_logs",
                to="workflow_v2.workflowexecution",
            ),
        ),
    ]
