# Generated by Django 4.2.1 on 2025-03-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_v2", "0011_update_wf_execution_fk_for_logs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executionlog",
            name="execution_id",
        ),
    ]
