# Generated by Django 4.2.1 on 2025-04-07 09:25

import logging

import django.db.models.deletion
from django.db import connection, migrations, models

logger = logging.getLogger(__name__)


def remove_execution_of_deleted_wfs(apps, schema_editor):
    """Removes records from workflow_execution which do not have an associated workflow."""
    with connection.cursor() as cursor:
        # Count records with invalid workflow_id
        cursor.execute(
            """
            SELECT COUNT(*) FROM workflow_execution
            WHERE workflow_id IS NOT NULL AND workflow_id::text NOT IN
            (SELECT id::text FROM workflow)
        """
        )
        invalid_count = cursor.fetchone()[0]

        if invalid_count > 0:
            logger.warning(
                f"Deleting '{invalid_count}' workflow executions with "
                "invalid workflow references"
            )

            # Delete records with invalid workflow_id
            cursor.execute(
                """
                DELETE FROM workflow_execution
                WHERE workflow_id IS NOT NULL AND workflow_id::text NOT IN
                (SELECT id::text FROM workflow)
            """
            )


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_v2", "0011_remove_filehistory_unique_workflow_cachekey_and_more"),
    ]

    operations = [
        # Run custom function to handle workflow_id conversion
        migrations.RunPython(
            remove_execution_of_deleted_wfs, reverse_code=migrations.RunPython.noop
        ),
        # Alter the field to be a foreign key while keeping the same column name
        migrations.AlterField(
            model_name="workflowexecution",
            name="workflow_id",
            field=models.ForeignKey(
                db_column="workflow_id",
                db_comment="Workflow to be executed",
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_executions",
                to="workflow_v2.workflow",
            ),
        ),
        # Rename the field in Django's ORM (doesn't affect the database column name)
        migrations.RenameField(
            model_name="workflowexecution",
            old_name="workflow_id",
            new_name="workflow",
        ),
    ]
