# Generated by Django 4.2.1 on 2025-06-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_v2", "0014_remove_filehistory_unique_workflow_cachekey_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["wf_execution", "event_time"], name="idx_wf_execution_event_time"
            ),
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["file_execution", "event_time"],
                name="idx_file_execution_event_time",
            ),
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["execution_id", "event_time"], name="idx_execution_id_event_time"
            ),
        ),
    ]
