# Generated by Django 4.2.1 on 2025-08-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_v2", "0015_executionlog_idx_wf_execution_event_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filehistory",
            name="file_reprocessing_interval",
            field=models.IntegerField(
                db_comment="Reprocessing interval in days. NULL means skip duplicates (no reprocessing)",
                null=True,
            ),
        ),
    ]
