# Generated by Django 4.2.1 on 2025-09-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_v2", "0015_executionlog_idx_wf_execution_event_time_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="filehistory",
            index=models.Index(
                fields=["workflow", "created_at"], name="idx_fh_workflow_created"
            ),
        ),
    ]
