# Generated by Django 4.2.1 on 2025-11-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_v2", "0017_workflow_shared_to_org_workflow_shared_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="filehistory",
            name="execution_count",
            field=models.IntegerField(
                db_comment="Number of times this file has been processed", default=1
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="max_file_execution_count",
            field=models.IntegerField(
                blank=True,
                db_comment="Maximum times a file can be executed. null=use org/global default. Only enforced for ETL/TASK workflows.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="filehistory",
            index=models.Index(
                fields=["workflow", "status"],
                name="idx_fh_wf_status",
            ),
        ),
        migrations.AddIndex(
            model_name="filehistory",
            index=models.Index(
                fields=["workflow", "execution_count"],
                name="idx_fh_wf_exec_cnt",
            ),
        ),
    ]
