# Generated by Django 4.2.1 on 2025-11-24 12:41

import django.core.validators
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_v2", "0017_workflow_shared_to_org_workflow_shared_users"),
    ]

    operations = [
        # Enable PostgreSQL trigram extension for fast partial text matching
        TrigramExtension(),
        migrations.AddField(
            model_name="filehistory",
            name="execution_count",
            field=models.IntegerField(
                db_comment="Number of times this file has been processed", default=1
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="max_file_execution_count",
            field=models.IntegerField(
                blank=True,
                db_comment="Maximum times a file can be executed. null=use org/global default. Only enforced for ETL/TASK workflows.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddIndex(
            model_name="filehistory",
            index=models.Index(fields=["workflow", "status"], name="idx_fh_wf_status"),
        ),
        migrations.AddIndex(
            model_name="filehistory",
            index=models.Index(
                fields=["workflow", "execution_count"], name="idx_fh_wf_exec_cnt"
            ),
        ),
        migrations.AddIndex(
            model_name="filehistory",
            index=models.Index(
                fields=["workflow", "file_path"], name="idx_fh_workflow_filepath"
            ),
        ),
        # Add GIN trigram index for fast partial file_path search (10-250x faster)
        migrations.AddIndex(
            model_name="filehistory",
            index=GinIndex(
                fields=["file_path"],
                name="idx_fh_file_path_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
