# Generated by Django 4.2.1 on 2025-11-24 12:41

import logging

import django.core.validators
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models

logger = logging.getLogger(__name__)


def ensure_pg_trgm_extension(apps, schema_editor):
    """Ensure pg_trgm extension is available and visible in search_path.

    This function handles all scenarios:
    1. Extension doesn't exist -> creates it in public schema
    2. Extension exists in public -> adds public to search_path
    3. Extension exists in another schema -> adds that schema to search_path
    """
    with schema_editor.connection.cursor() as cursor:
        # Check if extension exists and where
        cursor.execute("""
            SELECT extnamespace::regnamespace::text as schema
            FROM pg_extension
            WHERE extname = 'pg_trgm';
        """)
        result = cursor.fetchone()

        if result is None:
            # Extension doesn't exist - create it in public
            logger.info("pg_trgm extension not found, creating in public schema")
            cursor.execute("CREATE EXTENSION pg_trgm WITH SCHEMA public;")
            ext_schema = "public"
        else:
            ext_schema = result[0]
            logger.info(f"pg_trgm extension found in schema: {ext_schema}")

        # Ensure the extension's schema is in search_path
        # This makes gin_trgm_ops visible for the GinIndex creation
        cursor.execute(
            "SELECT set_config('search_path', "
            "current_setting('search_path') || ', ' || %s, false);",
            [ext_schema],
        )
        logger.info(f"Added {ext_schema} to search_path for gin_trgm_ops visibility")


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_v2", "0017_workflow_shared_to_org_workflow_shared_users"),
    ]

    operations = [
        # Ensure pg_trgm extension is available and visible for fast partial text matching
        migrations.RunPython(ensure_pg_trgm_extension, migrations.RunPython.noop),
        migrations.AddField(
            model_name="filehistory",
            name="execution_count",
            field=models.IntegerField(
                db_comment="Number of times this file has been processed", default=1
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="max_file_execution_count",
            field=models.IntegerField(
                blank=True,
                db_comment="Maximum times a file can be executed. null=use org/global default. Only enforced for ETL/TASK workflows.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddIndex(
            model_name="filehistory",
            index=models.Index(fields=["workflow", "status"], name="idx_fh_wf_status"),
        ),
        migrations.AddIndex(
            model_name="filehistory",
            index=models.Index(
                fields=["workflow", "execution_count"], name="idx_fh_wf_exec_cnt"
            ),
        ),
        migrations.AddIndex(
            model_name="filehistory",
            index=models.Index(
                fields=["workflow", "file_path"], name="idx_fh_workflow_filepath"
            ),
        ),
        # Add GIN trigram index for fast partial file_path search (10-250x faster)
        migrations.AddIndex(
            model_name="filehistory",
            index=GinIndex(
                fields=["file_path"],
                name="idx_fh_file_path_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
