# Generated by Django 4.2.1 on 2025-12-17

from django.db import migrations


class Migration(migrations.Migration):
    """Remove the trigram GIN index from FileHistory.

    This migration safely removes the pg_trgm GIN index that was added in 0018.
    The trigram index is not needed as we only require complete filepath search,
    not partial/fuzzy matching. Additionally, the TrigramExtension requires
    superuser privileges which may not be available on all PostgreSQL installations.

    This migration is safe to run on:
    - Production: Will drop the existing GIN index
    - New installations: Will be a no-op (index doesn't exist)
    """

    dependencies = [
        ("workflow_v2", "0018_filehistory_execution_count_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            # Forward: Drop the GIN index if it exists
            sql="DROP INDEX IF EXISTS idx_fh_file_path_trgm;",
            # Reverse: No-op - we don't want to recreate it
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
