# Generated by Django 4.2.1 on 2026-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_account_v2", "0002_organization_group_group_membership"),
        ("workflow_v2", "0019_remove_filehistory_trigram_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="shared_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_workflows",
                to="tenant_account_v2.organizationgroup",
            ),
        ),
    ]
