# Generated by Django 4.2.1 on 2026-06-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_v2", "0019_remove_filehistory_trigram_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="queue_message_id",
            field=models.BigIntegerField(
                db_comment="pg_queue_message.msg_id for PG-transport executions (the queue-row handle; task_id stays NULL on the PG path)",
                editable=False,
                null=True,
            ),
        ),
    ]
