# Generated by Django 4.2.30 on 2026-06-19 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_v2", "0005_alter_platformkey_organization"),
        ("workflow_v2", "0020_workflowexecution_file_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_comment="Foreign key reference to the Organization model.",
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_v2.organization",
            ),
        ),
    ]
