# Generated by Django 4.2.1 on 2026-06-26 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_v2", "0020_workflowexecution_queue_message_id"),
        ("workflow_v2", "0021_alter_workflow_organization"),
    ]

    operations = []
