# Generated by Django 4.2.30 on 2026-07-20 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_v2", "0022_absorb_shared_users"),
        ("workflow_v2", "0023_workflowexecution_active_by_workflow_idx"),
    ]

    operations = []
