# Generated by Django 4.2.30 on 2026-07-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_v2", "0024_merge_coowner_and_active_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["organization", "-modified_at"], name="workflow_org_modified_idx"
            ),
        ),
    ]
