# Generated by Django 4.2.1 on 2025-02-11 12:34

from django.db import migrations

STATUS_RENAME_MAP = {
    "ExecutionStatus.PENDING": "PENDING",
    "ExecutionStatus.INITIATED": "INITIATED",
    "ExecutionStatus.QUEUED": "QUEUED",
    "ExecutionStatus.READY": "READY",
    "ExecutionStatus.EXECUTING": "EXECUTING",
    "ExecutionStatus.COMPLETED": "COMPLETED",
    "ExecutionStatus.STOPPED": "STOPPED",
    "ExecutionStatus.ERROR": "ERROR",
}

REVERSE_STATUS_RENAME_MAP = {v: k for k, v in STATUS_RENAME_MAP.items()}


def rename_statuses_forward(apps, schema_editor):
    """Rename statuses by removing the 'ExecutionStatus.' prefix."""
    WorkflowFileExecution = apps.get_model("file_execution", "WorkflowFileExecution")
    for old_status, new_status in STATUS_RENAME_MAP.items():
        WorkflowFileExecution.objects.filter(status=old_status).update(
            status=new_status
        )


def rename_statuses_backward(apps, schema_editor):
    """Restore the original statuses with 'ExecutionStatus.' prefix."""
    WorkflowFileExecution = apps.get_model("file_execution", "WorkflowFileExecution")
    for new_status, old_status in REVERSE_STATUS_RENAME_MAP.items():
        WorkflowFileExecution.objects.filter(status=new_status).update(
            status=old_status
        )


class Migration(migrations.Migration):

    dependencies = [
        ("file_execution", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(rename_statuses_forward, rename_statuses_backward),
    ]
