# Generated by Django 4.2.1 on 2025-03-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_execution", "0003_alter_workflowfileexecution_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowfileexecution",
            name="status",
            field=models.TextField(
                choices=[
                    ("PENDING", "Pending"),
                    ("EXECUTING", "Executing"),
                    ("COMPLETED", "Completed"),
                    ("STOPPED", "Stopped"),
                    ("ERROR", "Error"),
                ],
                db_comment="Current status of the execution",
            ),
        ),
    ]
