# Generated by Django 4.2.1 on 2025-07-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_execution", "0005_workflowfileexecution_fs_metadata_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workflowfileexecution",
            index=models.Index(
                fields=["workflow_execution", "file_hash", "file_path", "status"],
                name="wf_file_hash_path_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowfileexecution",
            index=models.Index(
                fields=[
                    "workflow_execution",
                    "provider_file_uuid",
                    "file_path",
                    "status",
                ],
                name="wf_provider_uuid_path_stat_idx",
            ),
        ),
    ]
