# Generated by Django 4.2.1 on 2025-07-09 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tool_instance_v2", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toolinstance",
            name="input_db_connector",
        ),
        migrations.RemoveField(
            model_name="toolinstance",
            name="input_file_connector",
        ),
        migrations.RemoveField(
            model_name="toolinstance",
            name="output_db_connector",
        ),
        migrations.RemoveField(
            model_name="toolinstance",
            name="output_file_connector",
        ),
    ]
