# Generated by Django 4.2.1 on 2024-02-07 11:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("prompt_studio_core", "0003_merge_20240125_1501"),
        ("prompt_studio", "0003_remove_toolstudioprompt_updated_at_and_more"),
        ("prompt_profile_manager", "0003_merge_20240125_0530"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptStudioOutputManager",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_output_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "output",
                    models.CharField(db_comment="Field to store output"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_output_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_output_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_manager",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_output_linked_prompt",
                        to="prompt_profile_manager.profilemanager",
                    ),
                ),
                (
                    "prompt_id",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_output_linked_prompt",
                        to="prompt_studio.toolstudioprompt",
                    ),
                ),
                (
                    "tool_id",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_ouput_linked_tool",
                        to="prompt_studio_core.customtool",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
