# Generated by Django 4.2.1 on 2024-02-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_output_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptstudiooutputmanager",
            name="doc_name",
            field=models.CharField(
                blank=True,
                db_comment="Field to store the document name",
                editable=False,
                null=True,
            ),
        ),
    ]
