# Generated by Django 4.2.1 on 2024-02-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prompt_studio_output_manager",
            "0003_alter_promptstudiooutputmanager_doc_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptstudiooutputmanager",
            name="doc_name",
            field=models.CharField(
                db_comment="Field to store the document name"
            ),
        ),
    ]
