# Generated by Django 4.2.1 on 2024-02-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_studio_core", "0003_merge_20240125_1501"),
        ("prompt_studio", "0003_remove_toolstudioprompt_updated_at_and_more"),
        ("prompt_profile_manager", "0003_merge_20240125_0530"),
        (
            "prompt_studio_output_manager",
            "0004_alter_promptstudiooutputmanager_doc_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptstudiooutputmanager",
            name="profile_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompt_output_linked_prompt",
                to="prompt_profile_manager.profilemanager",
            ),
        ),
        migrations.AlterField(
            model_name="promptstudiooutputmanager",
            name="prompt_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompt_output_linked_prompt",
                to="prompt_studio.toolstudioprompt",
            ),
        ),
        migrations.AlterField(
            model_name="promptstudiooutputmanager",
            name="tool_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompt_ouput_linked_tool",
                to="prompt_studio_core.customtool",
            ),
        ),
    ]
