# Generated by Django 4.2.1 on 2024-03-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_profile_manager", "0006_alter_profilemanager_x2text"),
        ("prompt_studio", "0006_alter_toolstudioprompt_prompt_key_and_more"),
        ("prompt_studio_document_manager", "0001_initial"),
        ("prompt_studio_core", "0006_alter_customtool_summarize_as_source_and_more"),
        ("prompt_studio_output_manager", "0007_promptstudiooutputmanager_eval_metrics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promptstudiooutputmanager",
            name="doc_name",
        ),
        migrations.AddField(
            model_name="promptstudiooutputmanager",
            name="document_manager",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_output_linked_document_manager",
                to="prompt_studio_document_manager.documentmanager",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="promptstudiooutputmanager",
            name="profile_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_output_linked_prompt",
                to="prompt_profile_manager.profilemanager",
            ),
        ),
        migrations.AlterField(
            model_name="promptstudiooutputmanager",
            name="prompt_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_output_linked_prompt",
                to="prompt_studio.toolstudioprompt",
            ),
        ),
        migrations.AlterField(
            model_name="promptstudiooutputmanager",
            name="tool_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_ouput_linked_tool",
                to="prompt_studio_core.customtool",
            ),
        ),
    ]
