# Generated by Django 4.2.1 on 2024-03-11 05:20

from django.db import migrations


def delete_existing_rows(apps, _):
    promptstudiooutputmanager = apps.get_model(
        "prompt_studio_output_manager", "promptstudiooutputmanager"
    )
    promptstudiooutputmanager.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "prompt_studio_output_manager",
            "0007_promptstudiooutputmanager_eval_metrics",
        ),
    ]

    operations = [
        migrations.RunPython(
            delete_existing_rows, reverse_code=migrations.RunPython.noop
        ),
    ]
