# Generated by Django 4.2.1 on 2024-05-14 11:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prompt_studio_output_manager",
            "0011_promptstudiooutputmanager_is_single_pass_extract_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="promptstudiooutputmanager",
            name="run_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
