# Generated by Django 4.2.1 on 2024-06-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_studio_output_manager", "0013_promptstudiooutputmanager_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptstudiooutputmanager",
            name="context",
            field=models.TextField(
                blank=True, db_comment="Field to store chunks used", null=True
            ),
        ),
    ]
