# Generated by Django 4.2.1 on 2024-08-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prompt_studio_output_manager",
            "0014_alter_promptstudiooutputmanager_context",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="promptstudiooutputmanager",
            name="challenge_data",
            field=models.JSONField(
                blank=True, db_comment="Field to store challenge data", null=True
            ),
        ),
    ]
