# Generated by Django 4.2.1 on 2024-01-09 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canned_question", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cannedquestion",
            old_name="question_text",
            new_name="question",
        ),
        migrations.RemoveField(
            model_name="cannedquestion",
            name="answer_text",
        ),
        migrations.RemoveField(
            model_name="cannedquestion",
            name="document_id",
        ),
    ]
