# Generated by Django 4.2.1 on 2025-09-17 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pipeline_v2", "0002_remove_pipeline_unique_pipeline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="shared_to_org",
            field=models.BooleanField(
                db_comment="Whether this pipeline is shared with the entire organization",
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="shared_users",
            field=models.ManyToManyField(
                blank=True,
                db_comment="Users with whom this pipeline is shared",
                related_name="shared_pipelines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
