# Generated by Django 4.2.1 on 2026-02-17 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pipeline_v2", "0003_add_sharing_fields_to_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="co_owners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users with full ownership privileges",
                related_name="co_owned_pipelines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
