class LogType:
    LOG = "LOG"
    UPDATE = "UPDATE"
    COST = "COST"
    RESULT = "RESULT"
    SINGLE_STEP = "SINGLE_STEP_MESSAGE"


class LogLevel:
    ERROR = "ERROR"
    WARN = "WARN"
    INFO = "INFO"
    DEBUG = "DEBUG"


class Env:
    LOG_LEVEL = "LOG_LEVEL"
    LOG_PATH = "LOG_PATH"
    REDIS_HOST = "REDIS_HOST"
    REDIS_PORT = "REDIS_PORT"
    REDIS_USER = "REDIS_USER"
    REDIS_PASSWORD = "REDIS_PASSWORD"
    CELERY_BROKER_URL = "CELERY_BROKER_URL"
    TOOL_INSTANCE_ID = "TOOL_INSTANCE_ID"
    EXECUTION_ID = "EXECUTION_ID"
    ORGANIZATION_ID = "ORGANIZATION_ID"
    FILE_EXECUTION_ID = "FILE_EXECUTION_ID"
    MESSAGING_CHANNEL = "MESSAGING_CHANNEL"
    CONTAINER_NAME = "CONTAINER_NAME"
