# Generated by Django 4.2.1 on 2024-06-19 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPSProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_comment='Field to store the name of the Simple Prompt Studio Project.')),
            ],
            options={
                'db_table': 'sps_project',
            },
        ),
    ]
