# Generated by Django 4.2.1 on 2024-06-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sps_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spsproject',
            old_name='id',
            new_name='tool_id',
        ),
        migrations.RenameField(
            model_name='spsproject',
            old_name='name',
            new_name='tool_name',
        ),
    ]
