# Generated by Django 4.2.1 on 2026-06-11 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PgQueueMessage",
            fields=[
                ("msg_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("queue_name", models.TextField()),
                ("message", models.JSONField()),
                ("org_id", models.TextField(blank=True, default="")),
                ("enqueued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("vt", models.DateTimeField(default=django.utils.timezone.now)),
                ("read_ct", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "pg_queue_message",
                "indexes": [
                    models.Index(
                        fields=["queue_name", "vt", "msg_id"],
                        name="pg_queue_message_dequeue_idx",
                    )
                ],
            },
        ),
    ]
