# Generated by Django 4.2.1 on 2026-06-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pgqueuemessage",
            name="pg_queue_message_dequeue_idx",
        ),
        migrations.AddField(
            model_name="pgqueuemessage",
            name="priority",
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddIndex(
            model_name="pgqueuemessage",
            index=models.Index(
                models.F("queue_name"),
                models.OrderBy(models.F("priority"), descending=True),
                models.F("msg_id"),
                name="pg_queue_message_dequeue_idx",
            ),
        ),
    ]
