# Generated by Django 4.2.30 on 2026-08-05 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0002_pgqueuemessage_available_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PgPeriodicTask",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("task_name", models.TextField()),
                ("queue", models.TextField()),
                ("task_args", models.JSONField(default=list)),
                ("task_kwargs", models.JSONField(default=dict)),
                ("cron_string", models.TextField()),
                ("org_id", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                ("pg_owned", models.BooleanField(default=False)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pg_periodic_task",
                "indexes": [
                    models.Index(
                        fields=["pg_owned", "enabled", "next_run_at"],
                        name="pg_periodic_task_due_idx",
                    )
                ],
            },
        ),
    ]
