# Generated by Django 4.2.1 on 2026-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0002_remove_pgqueuemessage_pg_queue_message_dequeue_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pgqueuemessage",
            constraint=models.CheckConstraint(
                check=models.Q(("priority__gte", 1), ("priority__lte", 10)),
                name="pg_queue_message_priority_range",
            ),
        ),
    ]
