# Generated by Django 4.2.1 on 2026-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0002_remove_pgqueuemessage_pg_queue_message_dequeue_idx_and_more"),
    ]

    operations = [
        # `check=` is correct for the pinned Django (4.2). It's deprecated in
        # 5.1 in favour of `condition=` and removed in 6.0 — but fresh installs
        # always replay this under the Django we ship, so leave it as-is.
        # When the pin is bumped to >= 6.0, squash these migrations (or do the
        # behaviour-preserving `check=` -> `condition=` edit) as part of that
        # upgrade so a from-scratch migrate still runs.
        migrations.AddConstraint(
            model_name="pgqueuemessage",
            constraint=models.CheckConstraint(
                check=models.Q(("priority__gte", 1), ("priority__lte", 10)),
                name="pg_queue_message_priority_range",
            ),
        ),
    ]
