# Generated by Django 4.2.1 on 2026-06-12 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0003_pgqueuemessage_pg_queue_message_priority_range"),
    ]

    operations = [
        migrations.CreateModel(
            name="PgBarrierState",
            fields=[
                ("execution_id", models.TextField(primary_key=True, serialize=False)),
                ("remaining", models.IntegerField()),
                ("results", models.JSONField(default=list)),
                ("aborted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "pg_barrier_state",
                "indexes": [
                    models.Index(fields=["expires_at"], name="pg_barrier_expires_idx")
                ],
            },
        ),
    ]
