# Generated by Django 4.2.1 on 2026-06-15 10:35

import django.utils.timezone
from django.db import migrations, models


def seed_single_row(apps, schema_editor):
    """Seed the one lock row (free: leader='').

    Leader-election does a row ``UPDATE`` — the row must exist for any candidate
    to ever win. ``get_or_create`` keeps re-runs / squashes idempotent.
    """
    PgOrchestratorLock = apps.get_model("pg_queue", "PgOrchestratorLock")
    PgOrchestratorLock.objects.get_or_create(id=1, defaults={"leader": ""})


def unseed_single_row(apps, schema_editor):
    PgOrchestratorLock = apps.get_model("pg_queue", "PgOrchestratorLock")
    PgOrchestratorLock.objects.filter(id=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0004_pgbarrierstate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PgOrchestratorLock",
            fields=[
                ("id", models.IntegerField(default=1, primary_key=True, serialize=False)),
                ("leader", models.TextField(blank=True, default="")),
                ("acquired_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "pg_orchestrator_lock",
            },
        ),
        migrations.AddConstraint(
            model_name="pgorchestratorlock",
            constraint=models.CheckConstraint(
                check=models.Q(("id", 1)), name="pg_orchestrator_lock_single_row"
            ),
        ),
        migrations.RunPython(seed_single_row, unseed_single_row),
    ]
