# Generated by Django 4.2.1 on 2026-06-17 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0005_pgorchestratorlock"),
    ]

    operations = [
        migrations.CreateModel(
            name="PgBatchDedup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_id", models.TextField()),
                ("batch_index", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "pg_batch_dedup",
            },
        ),
        migrations.AddConstraint(
            model_name="pgbatchdedup",
            constraint=models.UniqueConstraint(
                fields=("execution_id", "batch_index"),
                name="pg_batch_dedup_exec_batch_uniq",
            ),
        ),
    ]
