# Generated by Django 4.2.1 on 2026-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0006_pgbatchdedup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pgbarrierstate",
            name="organization_id",
            field=models.TextField(blank=True, default=""),
        ),
    ]
