# Generated by Django 4.2.1 on 2026-06-18 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0007_pgbarrierstate_organization_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PgPeriodicSchedule",
            fields=[
                ("pipeline_id", models.UUIDField(primary_key=True, serialize=False)),
                ("organization_id", models.TextField(blank=True, default="")),
                ("workflow_id", models.UUIDField(blank=True, null=True)),
                ("pipeline_name", models.TextField(blank=True, default="")),
                ("cron_string", models.TextField()),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pg_periodic_schedule",
                "indexes": [
                    models.Index(
                        fields=["enabled", "next_run_at"], name="pg_sched_due_idx"
                    )
                ],
            },
        ),
    ]
