# Generated by Django 4.2.1 on 2026-06-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0008_pgperiodicschedule"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pgperiodicschedule",
            name="pg_periodic_schedule_due_idx",
        ),
        migrations.AddField(
            model_name="pgperiodicschedule",
            name="pg_owned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="pgperiodicschedule",
            index=models.Index(
                fields=["pg_owned", "enabled", "next_run_at"],
                name="pg_periodic_schedule_due_idx",
            ),
        ),
    ]
