# Generated by Django 4.2.1 on 2026-06-19 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pg_queue",
            "0009_remove_pgperiodicschedule_pg_periodic_schedule_due_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PgTaskResult",
            fields=[
                ("task_id", models.TextField(primary_key=True, serialize=False)),
                ("status", models.TextField()),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "pg_task_result",
                "indexes": [
                    models.Index(fields=["expires_at"], name="pg_task_result_expires_idx")
                ],
            },
        ),
    ]
