# Generated by Django 4.2.30 on 2026-07-02 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0011_pgbarrierstate_last_progress_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PgOrchestrationClaim",
            fields=[
                ("execution_id", models.TextField(primary_key=True, serialize=False)),
                ("claimed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "pg_orchestration_claim",
            },
        ),
    ]
