# Generated by Django 4.2.30 on 2026-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0012_pgorchestrationclaim"),
    ]

    operations = [
        migrations.AddField(
            model_name="pgorchestrationclaim",
            name="organization_id",
            field=models.TextField(blank=True, default=""),
        ),
    ]
