# Generated by Django 4.2.30 on 2026-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_queue", "0013_pgorchestrationclaim_organization_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pgqueuemessage",
            name="pg_queue_message_dequeue_idx",
        ),
        migrations.AddField(
            model_name="pgqueuemessage",
            name="state",
            field=models.TextField(default="ready"),
        ),
        # Django's AddField backfills every existing row to 'ready' then DROPs the
        # DB default (it manages defaults at the ORM layer). Re-add a DB-level
        # default so the schema is self-protecting: a raw INSERT that omits `state`
        # still lands a valid 'ready' row rather than a NOT-NULL violation.
        # (The ORM always sends state='ready' via the field default, so this guards
        # only raw SQL; insert_message_sql() also sets it explicitly — belt +
        # suspenders.) Metadata-only; touches no row data.
        migrations.RunSQL(
            sql="ALTER TABLE pg_queue_message ALTER COLUMN state SET DEFAULT 'ready'",
            reverse_sql="ALTER TABLE pg_queue_message ALTER COLUMN state DROP DEFAULT",
        ),
        # Deploy-safety backfill: the new claim keys off `state` and ignores `vt`,
        # but AddField set EVERY pre-existing row (including claimed-but-unacked
        # in-flight rows, which carry a future `vt`) to 'ready'. Without this, a
        # rolling deploy over a non-empty queue would make a still-processing
        # message instantly re-claimable → one-time double processing (absorbed by
        # the idempotency stack, but avoidable). Land genuinely in-flight rows as
        # 'claimed' so they stay invisible until their lease expires. No-op at the
        # first enablement (the queue table is empty while the flag is off).
        migrations.RunSQL(
            sql="UPDATE pg_queue_message SET state = 'claimed' WHERE vt > now()",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="pgqueuemessage",
            index=models.Index(
                models.F("queue_name"),
                models.OrderBy(models.F("priority"), descending=True),
                models.F("msg_id"),
                condition=models.Q(("state", "ready")),
                name="pg_queue_message_claim_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pgqueuemessage",
            index=models.Index(
                models.F("msg_id"),
                condition=models.Q(("state", "claimed")),
                name="pg_queue_message_claimed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pgqueuemessage",
            constraint=models.CheckConstraint(
                check=models.Q(("state__in", ["ready", "claimed"])),
                name="pg_queue_message_state_valid",
            ),
        ),
        # NOTE (UN-3445): performance tuning for the state-machine churn
        # (fillfactor + aggressive per-table autovacuum) is deliberately KEPT OUT of
        # this migration. Those are core-Postgres reloptions, but they are (a)
        # environment-specific tuning that belongs in the ops/deploy layer, not app
        # schema, and (b) potentially restricted by a locked-down managed role
        # (Cloud SQL / RDS / Azure), where a failed `ALTER TABLE SET (autovacuum_*)`
        # would abort the whole migration. The fix itself (state column + partial
        # indexes) is pure portable DDL and needs none of it. If a soak shows bloat,
        # apply the tuning per environment via ops (see the PR/runbook), not here.
    ]
