# Generated by Django 4.2.1 on 2024-01-15 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_routing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trafficrule",
            old_name="rule_value",
            new_name="rule",
        ),
    ]
