# Generated by Django - Squashed migration for lookup app

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Squashed initial migration for the lookup app.

    This migration creates all lookup-related models:
    - LookupProject: Main project configuration
    - LookupPromptTemplate: Prompt templates with variable detection
    - LookupDataSource: Reference data file management with versioning
    - LookupProfileManager: Adapter profiles for indexing/querying
    - LookupIndexManager: Index tracking for vector DB
    - PromptStudioLookupLink: Links between PS projects and Lookups
    - LookupExecutionAudit: Execution history and metrics
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account_v2", "0001_initial"),
        ("adapter_processor_v2", "0001_initial"),
    ]

    operations = [
        # 1. Create LookupProject model
        migrations.CreateModel(
            name="LookupProject",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when the record was created",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the Look-Up project", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the Look-Up project's purpose",
                        null=True,
                    ),
                ),
                (
                    "lookup_type",
                    models.CharField(
                        choices=[("static_data", "Static Data")],
                        default="static_data",
                        help_text="Type of Look-Up (only static_data for POC)",
                        max_length=50,
                    ),
                ),
                (
                    "reference_data_type",
                    models.CharField(
                        choices=[
                            ("vendor_catalog", "Vendor Catalog"),
                            ("product_catalog", "Product Catalog"),
                            ("customer_database", "Customer Database"),
                            ("pricing_data", "Pricing Data"),
                            ("compliance_rules", "Compliance Rules"),
                            ("custom", "Custom"),
                        ],
                        help_text="Category of reference data being stored",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this project is active"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the project",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("azure", "Azure OpenAI"),
                            ("custom", "Custom Provider"),
                        ],
                        help_text="LLM provider to use for matching",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        help_text="Specific model name (e.g., gpt-4-turbo, claude-3-opus)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "llm_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional LLM configuration (temperature, max_tokens, etc.)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this project",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_lookup_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lookup_projects",
                        to="account_v2.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Look-Up Project",
                "verbose_name_plural": "Look-Up Projects",
                "db_table": "lookup_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lookupproject",
            index=models.Index(fields=["organization"], name="lookup_proj_organiz_idx"),
        ),
        migrations.AddIndex(
            model_name="lookupproject",
            index=models.Index(fields=["created_by"], name="lookup_proj_created_idx"),
        ),
        migrations.AddIndex(
            model_name="lookupproject",
            index=models.Index(fields=["modified_at"], name="lookup_proj_modifie_idx"),
        ),
        # 2. Create LookupPromptTemplate model
        migrations.CreateModel(
            name="LookupPromptTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when the record was created",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for identification", max_length=255
                    ),
                ),
                (
                    "template_text",
                    models.TextField(help_text="Template with {{variable}} placeholders"),
                ),
                (
                    "llm_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="LLM configuration including adapter_id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active"
                    ),
                ),
                (
                    "variable_mappings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional documentation of variable mappings",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this template",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_lookup_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Parent Look-Up project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_template_link",
                        to="lookup.lookupproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Look-Up Prompt Template",
                "verbose_name_plural": "Look-Up Prompt Templates",
                "db_table": "lookup_prompt_templates",
                "ordering": ["-modified_at"],
            },
        ),
        # 3. Add template FK to LookupProject (after template is created)
        migrations.AddField(
            model_name="lookupproject",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Prompt template for this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="lookup.lookupprompttemplate",
            ),
        ),
        # 4. Create LookupDataSource model
        migrations.CreateModel(
            name="LookupDataSource",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when the record was created",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                ("file_path", models.TextField(help_text="Path in object storage")),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                            ("docx", "Word"),
                            ("txt", "Text"),
                            ("json", "JSON"),
                        ],
                        help_text="Type of file",
                        max_length=50,
                    ),
                ),
                (
                    "extracted_content_path",
                    models.TextField(
                        blank=True,
                        help_text="Path to extracted text in object storage",
                        null=True,
                    ),
                ),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Status of text extraction",
                        max_length=20,
                    ),
                ),
                (
                    "extraction_error",
                    models.TextField(
                        blank=True,
                        help_text="Error details if extraction failed",
                        null=True,
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(
                        default=1,
                        help_text="Version number of this data source (auto-incremented)",
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        default=True, help_text="Whether this is the latest version"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Parent Look-Up project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to="lookup.lookupproject",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this file",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="uploaded_lookup_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Look-Up Data Source",
                "verbose_name_plural": "Look-Up Data Sources",
                "db_table": "lookup_data_sources",
                "ordering": ["-version_number"],
                "unique_together": {("project", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="lookupdatasource",
            index=models.Index(fields=["project"], name="lookup_data_project_idx"),
        ),
        migrations.AddIndex(
            model_name="lookupdatasource",
            index=models.Index(
                fields=["project", "is_latest"], name="lookup_data_proj_latest_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lookupdatasource",
            index=models.Index(fields=["created_at"], name="lookup_data_created_idx"),
        ),
        migrations.AddIndex(
            model_name="lookupdatasource",
            index=models.Index(
                fields=["extraction_status"], name="lookup_data_extract_idx"
            ),
        ),
        # 5. Create LookupProfileManager model
        migrations.CreateModel(
            name="LookupProfileManager",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when the record was created",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "profile_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profile_name", models.TextField(db_comment="Name of the profile")),
                (
                    "chunk_size",
                    models.IntegerField(
                        db_comment="Size of text chunks for indexing", default=1000
                    ),
                ),
                (
                    "chunk_overlap",
                    models.IntegerField(
                        db_comment="Overlap between consecutive chunks", default=200
                    ),
                ),
                (
                    "similarity_top_k",
                    models.IntegerField(
                        db_comment="Number of top similar chunks to retrieve", default=5
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_comment="Whether this is the default profile for the project",
                        default=False,
                    ),
                ),
                (
                    "reindex",
                    models.BooleanField(
                        db_comment="Flag to trigger re-indexing of reference data",
                        default=False,
                    ),
                ),
                (
                    "lookup_project",
                    models.ForeignKey(
                        db_comment="Look-Up project this profile belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="lookup.lookupproject",
                    ),
                ),
                (
                    "vector_store",
                    models.ForeignKey(
                        db_comment="Vector database adapter for storing embeddings",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lookup_profiles_vector_store",
                        to="adapter_processor_v2.adapterinstance",
                    ),
                ),
                (
                    "embedding_model",
                    models.ForeignKey(
                        db_comment="Embedding model adapter for generating vectors",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lookup_profiles_embedding_model",
                        to="adapter_processor_v2.adapterinstance",
                    ),
                ),
                (
                    "llm",
                    models.ForeignKey(
                        db_comment="LLM adapter for query processing and response generation",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lookup_profiles_llm",
                        to="adapter_processor_v2.adapterinstance",
                    ),
                ),
                (
                    "x2text",
                    models.ForeignKey(
                        db_comment="X2Text adapter for extracting text from various file formats",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lookup_profiles_x2text",
                        to="adapter_processor_v2.adapterinstance",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookup_profile_managers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookup_profile_managers_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lookup Profile Manager",
                "verbose_name_plural": "Lookup Profile Managers",
                "db_table": "lookup_profile_manager",
            },
        ),
        migrations.AddConstraint(
            model_name="lookupprofilemanager",
            constraint=models.UniqueConstraint(
                fields=("lookup_project", "profile_name"),
                name="unique_lookup_project_profile_name_index",
            ),
        ),
        # 6. Create LookupIndexManager model
        migrations.CreateModel(
            name="LookupIndexManager",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when the record was created",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when the record was last modified",
                    ),
                ),
                (
                    "index_manager_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_index_id",
                    models.CharField(
                        blank=True,
                        db_comment="Raw index ID for vector DB",
                        editable=False,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "index_ids_history",
                    models.JSONField(
                        blank=False,
                        db_comment="List of all index IDs created for this data source",
                        default=list,
                        null=False,
                    ),
                ),
                (
                    "extraction_status",
                    models.JSONField(
                        blank=False,
                        db_comment='Extraction status per X2Text config: {x2text_config_hash: {"extracted": bool, "enable_highlight": bool, "error": str}}',
                        default=dict,
                        null=False,
                    ),
                ),
                (
                    "status",
                    models.JSONField(
                        blank=False,
                        db_comment="Extraction and indexing status",
                        default=dict,
                        null=False,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        db_comment="Reference data source being indexed",
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_managers",
                        to="lookup.lookupdatasource",
                    ),
                ),
                (
                    "profile_manager",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Profile used for indexing this data source",
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="index_managers",
                        to="lookup.lookupprofilemanager",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookup_index_managers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookup_index_managers_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lookup Index Manager",
                "verbose_name_plural": "Lookup Index Managers",
                "db_table": "lookup_index_manager",
            },
        ),
        migrations.AddConstraint(
            model_name="lookupindexmanager",
            constraint=models.UniqueConstraint(
                fields=("data_source", "profile_manager"),
                name="unique_data_source_profile_manager_index",
            ),
        ),
        # 7. Create PromptStudioLookupLink model
        migrations.CreateModel(
            name="PromptStudioLookupLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt_studio_project_id",
                    models.UUIDField(help_text="UUID of the Prompt Studio project"),
                ),
                (
                    "execution_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which this Look-Up executes (lower numbers first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lookup_project",
                    models.ForeignKey(
                        help_text="Linked Look-Up project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ps_links",
                        to="lookup.lookupproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt Studio Look-Up Link",
                "verbose_name_plural": "Prompt Studio Look-Up Links",
                "db_table": "prompt_studio_lookup_links",
                "ordering": ["execution_order", "created_at"],
                "unique_together": {("prompt_studio_project_id", "lookup_project")},
            },
        ),
        migrations.AddIndex(
            model_name="promptstudiolookuplink",
            index=models.Index(
                fields=["prompt_studio_project_id"], name="ps_lookup_link_ps_proj_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptstudiolookuplink",
            index=models.Index(
                fields=["lookup_project"], name="ps_lookup_link_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptstudiolookuplink",
            index=models.Index(
                fields=["prompt_studio_project_id", "execution_order"],
                name="ps_lookup_link_order_idx",
            ),
        ),
        # 8. Create LookupExecutionAudit model
        migrations.CreateModel(
            name="LookupExecutionAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt_studio_project_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Associated Prompt Studio project if applicable",
                        null=True,
                    ),
                ),
                (
                    "execution_id",
                    models.UUIDField(
                        help_text="Groups all Look-Ups in a single execution batch"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        help_text="Input data from Prompt Studio extraction"
                    ),
                ),
                (
                    "reference_data_version",
                    models.IntegerField(help_text="Version of reference data used"),
                ),
                (
                    "enriched_output",
                    models.JSONField(
                        blank=True, help_text="Enrichment data produced", null=True
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(help_text="LLM provider used", max_length=50),
                ),
                (
                    "llm_model",
                    models.CharField(help_text="LLM model used", max_length=100),
                ),
                ("llm_prompt", models.TextField(help_text="Full prompt sent to LLM")),
                (
                    "llm_response",
                    models.TextField(blank=True, help_text="Raw LLM response", null=True),
                ),
                (
                    "llm_response_cached",
                    models.BooleanField(
                        default=False, help_text="Whether response was from cache"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Total execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "llm_call_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="LLM API call time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        help_text="Execution status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if failed", null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence score from LLM (0.00 to 1.00)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the execution occurred"
                    ),
                ),
                (
                    "lookup_project",
                    models.ForeignKey(
                        help_text="Look-Up project that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_audits",
                        to="lookup.lookupproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Look-Up Execution Audit",
                "verbose_name_plural": "Look-Up Execution Audits",
                "db_table": "lookup_execution_audit",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lookupexecutionaudit",
            index=models.Index(fields=["lookup_project"], name="lookup_audit_proj_idx"),
        ),
        migrations.AddIndex(
            model_name="lookupexecutionaudit",
            index=models.Index(fields=["execution_id"], name="lookup_audit_exec_idx"),
        ),
        migrations.AddIndex(
            model_name="lookupexecutionaudit",
            index=models.Index(fields=["executed_at"], name="lookup_audit_time_idx"),
        ),
        migrations.AddIndex(
            model_name="lookupexecutionaudit",
            index=models.Index(fields=["status"], name="lookup_audit_status_idx"),
        ),
    ]
