# Generated by Django 4.2.1 on 2026-03-25 18:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account_v2", "0004_user_is_service_account"),
        ("api_v2", "0003_add_organization_rate_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalApiDeploymentKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(max_length=512)),
                ("key", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allow_all_deployments",
                    models.BooleanField(
                        db_comment="If True, this key can authenticate any API deployment in the org",
                        default=True,
                    ),
                ),
                (
                    "api_deployments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="global_api_deployment_keys",
                        to="api_v2.apideployment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="global_api_deployment_keys_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Foreign key reference to the Organization model.",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_v2.organization",
                    ),
                ),
            ],
            options={
                "db_table": "global_api_deployment_key",
            },
        ),
        migrations.AddConstraint(
            model_name="globalapideploymentkey",
            constraint=models.UniqueConstraint(
                fields=("name", "organization"),
                name="unique_global_api_deployment_key_name_per_org",
            ),
        ),
    ]
