[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "unstract-tool-sandbox"
version = "0.0.1"
description = "Unstract Tool Sandbox is a package to communicate with tool worker"
authors = [
    {name = "Zipstack Inc.", email = "devsupport@zipstack.com"},
]
dependencies = [
    "requests==2.31.0"
]
requires-python = ">=3.9"
readme = "README.md"
# license = {text = "MIT"}


[tool.pdm.build]
includes = ["src"]
package-dir = "src"
