name: Build and Push Tool Sidecar Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true
        type: string

run-name: "[${{ inputs.tag }}] Tool Sidecar Docker Build and Push"

env:
  REGISTRY: docker.io
  IMAGE_NAME: unstract/tool-sidecar

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for release
        if: github.event_name == 'release'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.tag }}

      - name: Checkout code for branch
        if: github.event_name != 'release'
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        working-directory: ./docker
        run: |
          DOCKER_VERSION_TAG=${{ github.event.release.tag_name || github.event.inputs.tag}}
          VERSION=$DOCKER_VERSION_TAG docker compose -f docker-compose.build.yaml build --no-cache tool-sidecar
          docker push unstract/tool-sidecar:$DOCKER_VERSION_TAG
          if [ "${{ github.event_name }}" = "release" ]; then
            docker tag unstract/tool-sidecar:$DOCKER_VERSION_TAG unstract/tool-sidecar:latest
            docker push unstract/tool-sidecar:latest
          fi
