name: Build and Push Tool Sidecar Image

on:
  push:
    branches:
      - main
    paths:
      - 'tool-sidecar/**'
      - '.github/workflows/docker-tool-sidecar-build-push.yaml'
  pull_request:
    paths:
      - 'tool-sidecar/**'
      - '.github/workflows/docker-tool-sidecar-build-push.yaml'
  workflow_dispatch:
    inputs:
      custom_tag:
        description: 'Custom tag for the image (e.g., dev, test-1)'
        required: false
        type: string

env:
  REGISTRY: docker.io
  IMAGE_NAME: unstract/tool-sidecar

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ inputs.custom_tag }},enable=${{ github.event_name == 'workflow_dispatch' && inputs.custom_tag != '' }}
            type=semver,pattern={{version}},enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./tool-sidecar
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
